export const CONTENT_DB = {

  // ========== 1º PERÍODO ==========

  "Introdução à Ciência Jurídica": {
    overview: `## Introdução à Ciência Jurídica\n\nDisciplina que apresenta o Direito como ciência, seus fundamentos, métodos e relação com outras áreas do conhecimento.\n\n**Temas centrais:**\n- Teoria Tridimensional de Miguel Reale: norma + fato + valor\n- Direito objetivo × subjetivo\n- Fontes do Direito: lei, costumes, jurisprudência, doutrina\n- Ramos do Direito: público e privado\n- Eficácia, vigência e validade da norma jurídica`,
    topics: `## Principais Tópicos\n\n### 1. Conceito de Direito\n- Teoria Tridimensional (Reale): fato + valor + norma\n- Direito Natural × Direito Positivo\n\n### 2. Fontes do Direito\n- Lei (principal fonte no civil law brasileiro)\n- Costumes, jurisprudência, doutrina, princípios gerais\n- Analogia (art. 4º LINDB)\n\n### 3. Norma Jurídica\n- Estrutura: hipótese de incidência + consequência\n- Caracteres: bilateralidade, imperatividade, coercibilidade\n- Vigência, validade e eficácia\n\n### 4. Ramos do Direito\n- Público: Constitucional, Administrativo, Penal, Processual\n- Privado: Civil, Empresarial, Trabalho`,
    summary: `## Resumo para Provas\n\n**Teoria Tridimensional de Miguel Reale:** O Direito é fato (social) + valor (ético) + norma (jurídica). Inseparáveis.\n\n**Fontes formais:** Lei (primária), costumes, jurisprudência, doutrina, princípios gerais, analogia.\n\n**Direito Objetivo:** o conjunto de normas (o ordenamento em si).\n**Direito Subjetivo:** a faculdade/prerrogativa de agir conforme a norma.\n\n**Vigência:** quando a lei está em vigor.\n**Validade:** conformidade com o ordenamento superior.\n**Eficácia:** capacidade de produzir efeitos reais na sociedade.\n\n**Vacatio legis (LINDB art. 1º):** 45 dias após publicação, salvo disposição contrária.`,
    quiz: [
      { question: "Segundo a Teoria Tridimensional de Miguel Reale, quais são os elementos do Direito?", options: { A: "Norma, poder e sociedade", B: "Fato, valor e norma", C: "Lei, costumes e jurisprudência", D: "Estado, povo e território" }, correct_answer: "B", explanation: "Miguel Reale concebeu o Direito como experiência tridimensional: fato social, valor ético e norma jurídica — todos inseparáveis." },
      { question: "Qual é a principal fonte do Direito no sistema jurídico brasileiro (civil law)?", options: { A: "A jurisprudência", B: "Os costumes", C: "A lei", D: "A doutrina" }, correct_answer: "C", explanation: "O Brasil adota o sistema romano-germânico (civil law), onde a lei escrita é a principal fonte do Direito." },
      { question: "O que é Direito Subjetivo?", options: { A: "O conjunto de normas jurídicas vigentes", B: "A faculdade de agir conforme o Direito objetivo", C: "As normas de Direito Público", D: "O poder coercitivo do Estado" }, correct_answer: "B", explanation: "Direito subjetivo é a prerrogativa que o ordenamento confere ao indivíduo de agir de determinada forma." },
      { question: "A analogia como método de integração do Direito consiste em:", options: { A: "Aplicar princípios éticos universais", B: "Usar os costumes locais para resolver lacunas", C: "Aplicar a uma situação não prevista a solução de caso semelhante regulado", D: "Interpretar a lei conforme sua finalidade" }, correct_answer: "C", explanation: "A analogia (art. 4º LINDB) aplica a um caso não regulado a norma prevista para hipótese semelhante." },
      { question: "A vigência de uma norma jurídica significa:", options: { A: "Que a norma é justa e eficaz", B: "Que a norma está apta a produzir efeitos, dentro de seu período de validade temporal", C: "Que a norma é amplamente obedecida", D: "Que foi declarada constitucional pelo STF" }, correct_answer: "B", explanation: "Vigência é a qualidade temporal da norma: indica o período em que ela está em vigor e pode ser aplicada." }
    ]
  },

  "Português Jurídico": {
    overview: `## Português Jurídico\n\nDisciplina que desenvolve a competência comunicativa escrita e oral no contexto jurídico.\n\n**Temas centrais:**\n- Linguagem jurídica: características e registro\n- Redação de peças jurídicas: petição inicial, contestação, recurso\n- Normas da ABNT para trabalhos jurídicos\n- Interpretação de textos legais\n- Argumentação jurídica e retórica`,
    topics: `## Principais Tópicos\n\n### 1. Linguagem Jurídica\n- Tecnicismo e precisão terminológica\n- Latinismos mais usados no Direito\n- Clareza, coesão e coerência textual\n\n### 2. Redação de Peças\n- Petição inicial: endereçamento, qualificação, fatos, direito, pedido\n- Contestação: preliminares e mérito\n- Recursos: estrutura e argumentação\n\n### 3. Argumentação Jurídica\n- Silogismo jurídico: premissa maior (norma) + menor (fato) = conclusão\n- Argumentos: a contrario sensu, ad absurdum, a fortiori\n\n### 4. Normas ABNT\n- NBR 14724 (trabalhos acadêmicos)\n- Citações diretas e indiretas\n- Referências bibliográficas`,
    summary: `## Resumo — Português Jurídico\n\n**Características da linguagem jurídica:** precisão, formalidade, uso de termos técnicos e latinismos, linguagem impessoal.\n\n**Latinismos comuns:**\n- *In dubio pro reo*: na dúvida, a favor do réu\n- *Habeas corpus*: que tenhas o corpo (liberdade de locomoção)\n- *Nulla poena sine lege*: não há pena sem lei prévia\n- *Res judicata*: coisa julgada\n- *Ex tunc/ex nunc*: retroativo/prospectivo\n\n**Petição inicial (art. 319 CPC):** endereçamento → qualificação das partes → fatos e fundamentos → pedido → valor da causa.\n\n**Silogismo jurídico:** Todo ladrão é punível (norma) + João furtou (fato) = João deve ser punido (conclusão).`,
    quiz: [
      { question: "O silogismo jurídico é composto por:", options: { A: "Fato, prova e sentença", B: "Premissa maior (norma) + premissa menor (fato) = conclusão jurídica", C: "Petição, contestação e sentença", D: "Lei, decreto e portaria" }, correct_answer: "B", explanation: "O silogismo jurídico segue a lógica clássica: a premissa maior é a norma jurídica, a menor é o fato concreto, e a conclusão é a decisão jurídica aplicável." },
      { question: "O latinismo 'in dubio pro reo' significa:", options: { A: "Em caso de dúvida, condena-se o réu", B: "Na dúvida, decide-se a favor do réu", C: "O réu deve provar sua inocência", D: "A dúvida beneficia o autor" }, correct_answer: "B", explanation: "'In dubio pro reo' é princípio do Direito Penal: na dúvida sobre a culpabilidade, o juiz deve absolver o réu." },
      { question: "Na estrutura da petição inicial, o pedido deve ser:", options: { A: "Genérico e abrangente para incluir todas as possibilidades", B: "Certo, determinado ou determinável", C: "Formulado apenas ao final, após a fundamentação", D: "Idêntico ao da contestação" }, correct_answer: "B", explanation: "Art. 322 CPC: o pedido deve ser certo. Art. 324: é lícito formular pedido genérico apenas nas hipóteses expressamente previstas (universalidade de bens, atos ilícitos, dependência de ato futuro)." }
    ]
  },

  "Metodologia de Pesquisa": {
    overview: `## Metodologia de Pesquisa Jurídica\n\nDisciplina que prepara o estudante para produzir conhecimento científico na área jurídica.\n\n**Temas centrais:**\n- Ciência e método científico\n- Tipos de pesquisa jurídica\n- Projeto de pesquisa e TCC\n- Normas ABNT para trabalhos acadêmicos\n- Fontes de pesquisa jurídica`,
    topics: `## Principais Tópicos\n\n### 1. Tipos de Pesquisa\n- Quanto à abordagem: quantitativa × qualitativa\n- Quanto aos objetivos: exploratória, descritiva, explicativa\n- Quanto aos procedimentos: bibliográfica, documental, de campo\n\n### 2. Projeto de Pesquisa\n- Tema e delimitação\n- Problema de pesquisa\n- Hipóteses\n- Objetivos (geral e específicos)\n- Justificativa\n- Metodologia\n- Referencial teórico\n\n### 3. Fontes Jurídicas de Pesquisa\n- Legislação: Planalto, Câmara, Senado\n- Jurisprudência: JusBrasil, STF, STJ, TJs\n- Doutrina: livros, artigos, revistas jurídicas\n- Bases: SciELO, CAPES`,
    summary: `## Resumo — Metodologia de Pesquisa\n\n**Pesquisa bibliográfica:** baseada em material já publicado (livros, artigos, teses). Mais comum no Direito.\n\n**Pesquisa documental:** usa documentos não publicados (processos, contratos, atos normativos).\n\n**Estrutura do TCC:** Introdução → Desenvolvimento (cap. 1, 2, 3) → Conclusão → Referências.\n\n**Citação direta curta:** até 3 linhas, entre aspas no texto.\n**Citação direta longa:** mais de 3 linhas, recuo de 4 cm, sem aspas, fonte menor.\n\n**Referência (ABNT NBR 6023):** SOBRENOME, Nome. *Título*. Edição. Local: Editora, Ano.`,
    quiz: [
      { question: "A pesquisa bibliográfica caracteriza-se por:", options: { A: "Coleta de dados por meio de entrevistas e questionários", B: "Ser elaborada com base em material já publicado", C: "Observação direta de fenômenos no campo", D: "Análise de documentos inéditos e não publicados" }, correct_answer: "B", explanation: "A pesquisa bibliográfica é baseada em obras já publicadas: livros, artigos científicos, teses, dissertações. É o tipo mais comum na pesquisa jurídica." },
      { question: "O problema de pesquisa deve ser formulado como:", options: { A: "Uma afirmação definitiva sobre o tema", B: "Uma hipótese a ser comprovada", C: "Uma pergunta que orientará toda a investigação", D: "Um objetivo geral do trabalho" }, correct_answer: "C", explanation: "O problema de pesquisa é formulado como uma pergunta clara e delimitada, que toda a pesquisa buscará responder." }
    ]
  },

  "Teoria Geral do Estado e Ciência Política": {
    overview: `## Teoria Geral do Estado e Ciência Política\n\nEstudo do Estado como organização política, seus elementos, formas e fundamentos teóricos.\n\n**Temas centrais:**\n- Conceito, elementos e origem do Estado\n- Formas de Estado e de governo\n- Separação dos poderes\n- Democracia e legitimidade\n- Estado Democrático de Direito`,
    topics: `## Principais Tópicos\n\n### 1. Conceito e Elementos do Estado\n- Elementos: povo + território + soberania (governo)\n- Teorias da origem: contratualismo (Hobbes, Locke, Rousseau)\n- Personalidade jurídica do Estado\n\n### 2. Formas de Estado\n- Unitário: poder centralizado\n- Federal: descentralização política\n- Confederação: aliança de Estados soberanos\n\n### 3. Formas de Governo\n- República: mandato, eletividade, responsabilidade\n- Monarquia: hereditariedade, vitaliciedade\n\n### 4. Sistemas de Governo\n- Presidencialismo: chefe de Estado = chefe de Governo\n- Parlamentarismo: separação entre chefe de Estado e de Governo\n\n### 5. Separação dos Poderes (Montesquieu)\n- Legislativo, Executivo e Judiciário\n- Sistema de freios e contrapesos`,
    summary: `## Resumo — Teoria Geral do Estado\n\n**Elementos do Estado:** povo (elemento humano), território (elemento físico) e soberania/governo (elemento político).\n\n**Contratualistas:**\n- Hobbes (*Leviatã*): estado de natureza = guerra; contrato cria Estado absoluto\n- Locke: estado de natureza = paz relativa; contrato para proteger propriedade\n- Rousseau (*Contrato Social*): soberania popular; vontade geral\n\n**Brasil:** Estado Democrático de Direito, forma federativa, sistema presidencialista, forma republicana.\n\n**Montesquieu (tripartição dos poderes):** Legislativo (faz as leis), Executivo (aplica as leis), Judiciário (julga conflitos). Freios e contrapesos evitam concentração de poder.`,
    quiz: [
      { question: "São elementos constitutivos do Estado:", options: { A: "Constituição, governo e população", B: "Povo, território e soberania", C: "Lei, justiça e democracia", D: "Nação, idioma e religião" }, correct_answer: "B", explanation: "Os três elementos do Estado são: povo (elemento pessoal), território (elemento espacial) e soberania/governo (elemento político)." },
      { question: "No presidencialismo, diferentemente do parlamentarismo:", options: { A: "O chefe de Estado é eleito pelo Parlamento", B: "O chefe de Estado e o chefe de Governo são a mesma pessoa, eleita pelo povo", C: "O Poder Executivo é subordinado ao Legislativo", D: "O mandato presidencial é vitalício" }, correct_answer: "B", explanation: "No presidencialismo (adotado no Brasil), o Presidente acumula as funções de chefe de Estado e de Governo, sendo eleito diretamente pelo povo por mandato fixo." }
    ]
  },

  // ========== 2º PERÍODO ==========

  "Direito Constitucional I": {
    overview: `## Direito Constitucional I\n\n**Ementa:** Teoria da Constituição, Poder Constituinte, princípios fundamentais da CF/88, direitos e garantias fundamentais.\n\n**Temas principais:**\n- Conceito e classificação das constituições\n- Poder Constituinte originário e derivado\n- Princípios fundamentais (arts. 1º ao 4º CF)\n- Direitos individuais e coletivos (art. 5º CF)\n- Direitos sociais (arts. 6º ao 11 CF)\n\n**Importância:** Base de todo o ordenamento jurídico. Essencial para OAB e todos os concursos.`,
    topics: `## Principais Tópicos\n\n### 1. Teoria da Constituição\n- Conceito material e formal\n- Classificações: rígida/flexível, escrita/costumeira, promulgada/outorgada\n- Supremacia constitucional\n\n### 2. Poder Constituinte\n- Originário: ilimitado, inicial, incondicionado\n- Derivado reformador: limitado pelas cláusulas pétreas (art. 60 §4º)\n- Emendas Constitucionais: 3/5 em 2 turnos\n\n### 3. Princípios Fundamentais (arts. 1º-4º)\n- Fundamentos (art. 1º): SCDVP\n- Objetivos (art. 3º): construir sociedade livre, erradicar pobreza, reduzir desigualdades, promover bem\n- Relações internacionais (art. 4º)\n\n### 4. Direitos Fundamentais (art. 5º)\n- Dimensões/gerações: 1ª (liberdade), 2ª (igualdade), 3ª (fraternidade)\n- Remédios: HC, MS, HD, MI, AP\n- Características: universalidade, irrenunciabilidade, imprescritibilidade\n\n### 5. Direitos Sociais (arts. 6º-11)\n- Direitos do trabalhador (art. 7º): 34 incisos\n- Direito de greve (art. 9º)`,
    summary: `## Resumo para Provas — Direito Constitucional I\n\n**Cláusulas pétreas (art. 60, §4º CF):**\n1. Forma federativa de Estado\n2. Voto direto, secreto, universal e periódico\n3. Separação dos Poderes\n4. Direitos e garantias individuais\n\n**Emenda Constitucional:** proposta por 1/3 da Câmara ou Senado, Presidente, ou maioria das Assembleias. Aprovada em 2 turnos, por 3/5 de cada Casa.\n\n**Fundamentos (art. 1º) — SCDVP:**\nSoberania · Cidadania · Dignidade · Valores sociais · Pluralismo político\n\n**Remédios constitucionais (art. 5º):**\n- HC (LXVIII): liberdade de locomoção\n- MS (LXIX): direito líquido e certo não amparado por HC/HD\n- HD (LXXII): informações pessoais em bancos de dados\n- MI (LXXI): inviabilização de direito por falta de norma regulamentadora\n- AP (LXXIII): atos lesivos ao patrimônio público\n\n**CF/88 é:** rígida, escrita, dogmática, promulgada, analítica (extensa).`,
    quiz: [
      { question: "São cláusulas pétreas da CF/88, EXCETO:", options: { A: "A forma federativa de Estado", B: "O voto direto, secreto, universal e periódico", C: "A separação dos Poderes", D: "O sistema presidencialista de governo" }, correct_answer: "D", explanation: "O sistema de governo (presidencialismo) NÃO é cláusula pétrea — pode ser alterado por emenda. As cláusulas pétreas estão no art. 60, §4º CF." },
      { question: "O Poder Constituinte Originário caracteriza-se por ser:", options: { A: "Limitado pela constituição anterior", B: "Ilimitado, inicial e incondicionado", C: "Subordinado ao Poder Constituinte Derivado", D: "Condicionado por normas de direito internacional" }, correct_answer: "B", explanation: "O Poder Constituinte Originário é ilimitado (sem restrições jurídicas), inicial (inaugura nova ordem) e incondicionado (não obedece forma prévia)." },
      { question: "O habeas corpus protege:", options: { A: "Direito líquido e certo não amparado por habeas data", B: "A liberdade de locomoção ameaçada ou violada por ilegalidade ou abuso de poder", C: "O conhecimento de informações pessoais em bancos de dados", D: "Direitos coletivos difusos" }, correct_answer: "B", explanation: "Art. 5º, LXVIII CF: o habeas corpus protege a liberdade de locomoção contra violência ou coação por ilegalidade ou abuso de poder." },
      { question: "São fundamentos da República Federativa do Brasil (art. 1º CF):", options: { A: "Soberania, cidadania e separação dos poderes", B: "Dignidade, pluralismo e isonomia", C: "Soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e pluralismo político", D: "Democracia, federalismo e república" }, correct_answer: "C", explanation: "Art. 1º CF: I-soberania, II-cidadania, III-dignidade da pessoa humana, IV-valores sociais do trabalho e da livre iniciativa, V-pluralismo político." },
      { question: "Quantos turnos e qual quórum são necessários para aprovação de emenda constitucional?", options: { A: "1 turno, maioria absoluta em cada Casa", B: "2 turnos, 3/5 dos membros em cada Casa", C: "2 turnos, maioria simples", D: "1 turno, 2/3 dos membros" }, correct_answer: "B", explanation: "Art. 60, §2º CF: a emenda é aprovada em cada Casa do Congresso, em dois turnos, por três quintos dos respectivos membros." }
    ]
  },

  "Direito Civil I (Parte Geral)": {
    overview: `## Direito Civil I — Parte Geral\n\n**Ementa:** Pessoas naturais e jurídicas, bens, fatos e atos jurídicos, negócio jurídico, prescrição e decadência.\n\n**Temas principais:**\n- Personalidade jurídica e capacidade civil\n- Pessoas jurídicas de direito público e privado\n- Classificação dos bens\n- Negócio jurídico: elementos, vícios, invalidade\n- Prescrição × Decadência`,
    topics: `## Principais Tópicos\n\n### 1. Pessoa Natural\n- Personalidade: adquirida com nascimento com vida\n- Nascituro: direitos resguardados desde a concepção\n- Capacidade de direito (todos têm) × capacidade de fato\n- Incapacidade absoluta: menor de 16 anos (apenas)\n- Incapacidade relativa: 16-18 anos, ébrios habituais, pródigos\n\n### 2. Pessoa Jurídica\n- Associações, sociedades, fundações\n- Desconsideração da personalidade (art. 50 CC): desvio de finalidade ou confusão patrimonial\n\n### 3. Bens\n- Móveis × imóveis; fungíveis × infungíveis; consumíveis × inconsumíveis\n- Bens públicos (uso comum, uso especial, dominicais)\n\n### 4. Negócio Jurídico\n- Elementos essenciais: agente capaz + objeto lícito + forma prescrita/não defesa\n- Vícios do consentimento: erro, dolo, coação, estado de perigo, lesão → anulabilidade\n- Vícios sociais: simulação → nulidade; fraude contra credores → anulabilidade\n\n### 5. Prescrição × Decadência\n- Prescrição: extingue pretensão. Pode ser suspensa/interrompida.\n- Decadência: extingue o direito. Não se interrompe (salvo lei).\n- Prazo geral de prescrição: 10 anos (art. 205 CC)`,
    summary: `## Resumo para Provas — Direito Civil I\n\n**Personalidade:** começa com nascimento com vida (art. 2º CC). Nascituro tem direitos resguardados.\n\n**Incapacidade (pós-EPD/2015):**\n- Absoluta: APENAS menores de 16 anos\n- Relativa: 16-18 anos, ébrios habituais, viciados, pródigos\n\n**Nulidade absoluta:** agente abs. incapaz, objeto ilícito/impossível/indeterminável, simulação, fraude à lei.\n**Anulabilidade:** agente rel. incapaz, vícios do consentimento (erro, dolo, coação, estado de perigo, lesão), fraude contra credores.\n\n**Prescrição × Decadência:**\n| | Prescrição | Decadência |\n|---|---|---|\n| Extingue | A pretensão | O direito |\n| Interrompe? | Sim | Não (regra) |\n| Renúncia? | Sim (após consumada) | Não |\n| Prazo geral | 10 anos | Depende da lei |`,
    quiz: [
      { question: "Após o Estatuto da Pessoa com Deficiência, são absolutamente incapazes:", options: { A: "Os menores de 16 anos e os que não podem exprimir vontade", B: "Apenas os menores de 16 anos", C: "Os menores de 18 anos", D: "Os portadores de doença mental e menores de 16 anos" }, correct_answer: "B", explanation: "Com a Lei 13.146/2015, o art. 3º CC passou a ter apenas UMA hipótese de incapacidade absoluta: menores de 16 anos." },
      { question: "A simulação no negócio jurídico gera:", options: { A: "Anulabilidade, prazo decadencial de 4 anos", B: "Ineficácia relativa perante terceiros", C: "Nulidade absoluta", D: "Invalidade somente se houver dano" }, correct_answer: "C", explanation: "Art. 167 CC: é NULO o negócio jurídico simulado. Simulação é vício social que gera nulidade absoluta." },
      { question: "A prescrição extingue:", options: { A: "O direito subjetivo", B: "A pretensão do titular do direito", C: "Apenas o direito de ação", D: "A relação jurídica por inteiro" }, correct_answer: "B", explanation: "Art. 189 CC: violado o direito, nasce para o titular a pretensão. A prescrição extingue a pretensão (e não o direito em si)." },
      { question: "A desconsideração da personalidade jurídica (art. 50 CC) exige:", options: { A: "Apenas que a empresa tenha prejuízo", B: "Abuso caracterizado por desvio de finalidade ou confusão patrimonial", C: "Requerimento do sócio majoritário", D: "Aprovação em assembleia" }, correct_answer: "B", explanation: "Art. 50 CC: a desconsideração é cabível em caso de abuso da personalidade jurídica, caracterizado por desvio de finalidade OU confusão patrimonial." },
      { question: "São bens imóveis por determinação legal:", options: { A: "Terras e construções", B: "Direitos reais sobre imóveis e as ações que os asseguram", C: "Árvores e frutos pendentes", D: "Materiais de construção" }, correct_answer: "B", explanation: "Art. 80 CC: consideram-se imóveis para efeitos legais: os direitos reais sobre imóveis e as ações que os asseguram, e o direito à sucessão aberta." }
    ]
  },

  "Direito Penal I": {
    overview: `## Direito Penal I\n\n**Ementa:** Princípios penais, lei penal, teoria do crime, tipicidade, ilicitude e culpabilidade.\n\n**Temas principais:**\n- Princípios constitucionais do Direito Penal\n- Aplicação da lei penal no tempo e espaço\n- Teoria do Crime: conceito analítico\n- Excludentes de ilicitude\n- Culpabilidade e imputabilidade`,
    topics: `## Principais Tópicos\n\n### 1. Princípios Penais\n- Legalidade: nullum crimen, nulla poena sine lege (art. 1º CP + art. 5º, XXXIX CF)\n- Anterioridade, irretroatividade (salvo lei benéfica)\n- Lesividade: só pune condutas que lesam bens jurídicos alheios\n- Culpabilidade: responsabilidade pessoal\n- Individualização da pena (art. 5º, XLVI CF)\n\n### 2. Lei Penal no Tempo\n- Irretroatividade da lei mais gravosa\n- Retroatividade da lei mais benéfica (lex mitior) — art. 5º, XL CF\n- Abolitio criminis: extingue a punibilidade\n- Combinação de leis: proibida (STJ/STF)\n\n### 3. Teoria do Crime (conceito analítico)\n- Fato típico: conduta + resultado + nexo causal + tipicidade\n- Ilicitude: contrariedade ao ordenamento\n- Culpabilidade: imputabilidade + pot. consciência da ilicitude + exigibilidade de conduta diversa\n\n### 4. Excludentes de Ilicitude (art. 23 CP)\n- Estado de necessidade\n- Legítima defesa\n- Estrito cumprimento do dever legal\n- Exercício regular do direito\n\n### 5. Dolo e Culpa\n- Dolo direto: quis o resultado\n- Dolo eventual: assumiu o risco\n- Culpa consciente: previu mas confiou que não ocorreria\n- Culpa inconsciente: não previu, mas deveria`,
    summary: `## Resumo para Provas — Direito Penal I\n\n**Legalidade (art. 1º CP):** não há crime sem lei anterior que o defina, nem pena sem lei anterior que a comine.\n\n**Lei benéfica retroage** mesmo após sentença transitada em julgado (art. 2º, §único CP).\n\n**Excludentes de ilicitude (art. 23 CP):**\n- **Legítima defesa (art. 25):** agressão injusta + atual/iminente + meios necessários usados moderadamente\n- **Estado de necessidade (art. 24):** perigo atual + não provocado + inevitável + bem de menor valor sacrificado\n- **Excesso (art. 23, §único):** punível a título de dolo ou culpa\n\n**Imputabilidade:** a partir de 18 anos. Doença mental que retire o entendimento → inimputável → medida de segurança.\n\n**Dolo × culpa:**\n- Dolo eventual ≠ culpa consciente: no dolo eventual, o agente ACEITA o resultado; na culpa consciente, confia que não vai ocorrer.`,
    quiz: [
      { question: "O princípio da legalidade penal está previsto:", options: { A: "Art. 1º CP e art. 5º, XXXIX CF", B: "Art. 59 CP", C: "Art. 5º, XL CF", D: "Art. 23 CP" }, correct_answer: "A", explanation: "O princípio da legalidade está no art. 1º CP ('Não há crime sem lei anterior') e no art. 5º, XXXIX CF (não há crime ou pena sem lei anterior que os defina/comine)." },
      { question: "A lei penal mais benéfica:", options: { A: "Nunca retroage", B: "Retroage apenas se o processo estiver em andamento", C: "Retroage para alcançar fatos anteriores, mesmo com sentença transitada em julgado", D: "Retroage apenas para crimes hediondos" }, correct_answer: "C", explanation: "Art. 5º, XL CF e art. 2º, §único CP: a lei posterior mais benéfica retroage, ainda que haja sentença condenatória transitada em julgado." },
      { question: "A legítima defesa (art. 25 CP) exige:", options: { A: "Agressão justa, atual e uso de qualquer meio", B: "Agressão injusta, atual ou iminente, e uso moderado dos meios necessários", C: "Perigo atual e sacrifício de bem de menor valor", D: "Cumprimento de ordem judicial" }, correct_answer: "B", explanation: "Art. 25 CP: legítima defesa = usar moderadamente os meios necessários para repelir injusta agressão, atual ou iminente, a direito seu ou de outrem." },
      { question: "A 'abolitio criminis' consiste em:", options: { A: "Lei mais severa criando novo tipo penal", B: "Extinção do crime por prescrição", C: "Lei posterior que deixa de tipificar conduta como crime, extinguindo a punibilidade", D: "Causa de aumento de pena" }, correct_answer: "C", explanation: "Abolitio criminis: lei posterior deixa de considerar criminosa determinada conduta → extingue a punibilidade para todos (art. 2º CP)." },
      { question: "Qual a diferença entre dolo eventual e culpa consciente?", options: { A: "São idênticos na prática jurídica", B: "No dolo eventual o agente aceita o resultado; na culpa consciente confia que não ocorrerá", C: "A culpa consciente tem pena maior", D: "Só o dolo eventual admite excludente de ilicitude" }, correct_answer: "B", explanation: "Dolo eventual: o agente prevê e ACEITA (assume o risco) do resultado. Culpa consciente: prevê o resultado, mas acredita sinceramente que pode evitá-lo." }
    ]
  },

  "Filosofia do Direito": {
    overview: `## Filosofia do Direito\n\nDisciplina que investiga os fundamentos filosóficos do Direito: o que é justo, o que fundamenta a obrigação jurídica e qual a relação entre Direito e moral.\n\n**Temas centrais:**\n- Jusnaturalismo × Juspositivismo\n- Teoria pura do Direito (Kelsen)\n- Hermenêutica filosófica e Direito\n- Direito, moral e justiça\n- Bioética e novos direitos`,
    topics: `## Principais Tópicos\n\n### 1. Jusnaturalismo\n- Direito natural: anterior e superior ao Direito positivo\n- Bases: razão, natureza humana, vontade divina\n- Influência na Declaração dos Direitos do Homem (1789)\n\n### 2. Juspositivismo\n- Direito = norma posta pelo Estado\n- Kelsen: Teoria Pura do Direito, norma fundamental, pirâmide normativa\n- Separação entre Direito e moral\n\n### 3. Pós-Positivismo\n- Princípios como normas jurídicas (Dworkin, Alexy)\n- Ponderação de princípios\n- Direito como integridade\n\n### 4. Justiça\n- Aristóteles: justiça distributiva × comutativa\n- Rawls: véu da ignorância, princípios da justiça\n\n### 5. Hermenêutica\n- Gadamer: fusão de horizontes\n- Aplicação ao Direito: interpretação criativa`,
    summary: `## Resumo — Filosofia do Direito\n\n**Jusnaturalismo:** existe um Direito natural, superior ao positivo, fundado na razão ou na natureza humana. Serve como parâmetro de justiça para o Direito posto.\n\n**Juspositivismo (Kelsen):** o Direito é apenas a norma posta pelo Estado. A Teoria Pura separa Direito de moral e política. A norma fundamental (Grundnorm) fundamenta todo o ordenamento.\n\n**Pirâmide de Kelsen:** CF → leis → decretos → atos administrativos. Cada norma busca fundamento na superior.\n\n**Pós-positivismo (Dworkin/Alexy):** princípios são normas com estrutura diferente das regras. Conflito de regras: tudo ou nada. Colisão de princípios: ponderação.\n\n**Justiça distributiva (Aristóteles):** distribuição proporcional de bens e encargos conforme os méritos.`,
    quiz: [
      { question: "Para Hans Kelsen, o Direito é:", options: { A: "Um conjunto de valores morais superiores", B: "A norma posta pelo Estado, separada da moral e da política", C: "A expressão da vontade popular", D: "A concretização do Direito Natural" }, correct_answer: "B", explanation: "Kelsen (positivismo jurídico): o Direito é apenas a norma posta pelo Estado. A Teoria Pura do Direito separa rigorosamente o Direito da moral, política e sociologia." },
      { question: "A diferença entre regras e princípios, segundo Robert Alexy, é que:", options: { A: "Princípios são mais antigos que as regras", B: "Regras se aplicam em graus; princípios tudo ou nada", C: "Regras são aplicadas tudo ou nada; princípios são mandados de otimização aplicados por ponderação", D: "Princípios têm hierarquia inferior às regras" }, correct_answer: "C", explanation: "Para Alexy, regras são normas definitivas (tudo ou nada). Princípios são mandados de otimização — devem ser realizados na maior medida possível, sujeitos à ponderação em caso de colisão." }
    ]
  },

  // ========== 3º PERÍODO ==========

  "Hermenêutica Jurídica": {
    overview: `## Hermenêutica Jurídica\n\nCiência que estuda os princípios e regras para interpretação e aplicação do Direito.\n\n**Temas centrais:**\n- Conceito de interpretação e integração jurídica\n- Métodos de interpretação\n- Lacunas do Direito e formas de integração\n- LINDB — Lei de Introdução às Normas do Direito Brasileiro\n- Conflito de normas no tempo e espaço`,
    topics: `## Principais Tópicos\n\n### 1. Métodos de Interpretação\n- Gramatical/literal: sentido das palavras\n- Lógico: coerência interna da norma\n- Sistemático: contexto do ordenamento jurídico\n- Histórico: origem e evolução legislativa\n- Teleológico: finalidade da lei (art. 5º LINDB)\n\n### 2. Quanto ao Resultado\n- Declarativa: lei diz exatamente o que quer\n- Extensiva: lei disse menos do que quis\n- Restritiva: lei disse mais do que quis\n\n### 3. Integração — Lacunas (art. 4º LINDB)\n- 1ª: Analogia\n- 2ª: Costumes\n- 3ª: Princípios gerais do Direito\n\n### 4. LINDB — Pontos Essenciais\n- Vacatio legis: 45 dias (Brasil) / 3 meses (exterior)\n- Irretroatividade: respeita ato jurídico perfeito, direito adquirido e coisa julgada (art. 6º)\n- Lei não perde vigência por desuso`,
    summary: `## Resumo — Hermenêutica\n\n**Integração (art. 4º LINDB):** analogia → costumes → princípios gerais do Direito.\n\n**Vacatio legis (art. 1º LINDB):** 45 dias após publicação (Brasil); 3 meses (exterior), salvo disposição contrária.\n\n**Irretroatividade:** a lei nova não atinge:\n- **Ato jurídico perfeito:** já consumado segundo a lei do tempo\n- **Direito adquirido:** já incorporado ao patrimônio\n- **Coisa julgada:** decisão judicial definitiva e irrecorrível\n\n**Teleologia (art. 5º LINDB):** na aplicação da lei, o juiz atenderá aos fins sociais e às exigências do bem comum.\n\n**Hermenêutica constitucional:** princípios específicos — unidade da Constituição, concordância prática, força normativa, máxima efetividade.`,
    quiz: [
      { question: "Segundo a LINDB, quando a lei é omissa, o juiz decide usando:", options: { A: "Princípios gerais, costumes, analogia", B: "Analogia, costumes e princípios gerais do Direito", C: "Costumes, analogia e equidade", D: "Doutrina, jurisprudência e analogia" }, correct_answer: "B", explanation: "Art. 4º LINDB: o juiz usa, na ordem: analogia → costumes → princípios gerais do Direito." },
      { question: "O prazo de vacatio legis previsto na LINDB é:", options: { A: "15 dias", B: "30 dias", C: "45 dias", D: "60 dias" }, correct_answer: "C", explanation: "Art. 1º LINDB: salvo disposição contrária, a lei brasileira começa a vigorar 45 dias após publicação oficial." },
      { question: "Na interpretação extensiva:", options: { A: "O intérprete ultrapassa o que o legislador quis dizer", B: "A lei disse menos do que queria; o intérprete amplia o sentido", C: "A lei é aplicada por analogia", D: "O juiz cria norma para suprir lacuna" }, correct_answer: "B", explanation: "Interpretação extensiva: a lei 'disse menos do que queria dizer' (minus dixit quam voluit). O intérprete amplia as palavras para alcançar o real intento do legislador." }
    ]
  },

  "Direito Constitucional II": {
    overview: `## Direito Constitucional II\n\n**Ementa:** Organização do Estado, repartição de competências, Poderes Legislativo e Executivo, processo legislativo.\n\n**Temas principais:**\n- Organização político-administrativa (arts. 18-43 CF)\n- Repartição de competências\n- Poder Legislativo: estrutura e atribuições\n- Processo legislativo\n- Poder Executivo e responsabilidade presidencial`,
    topics: `## Principais Tópicos\n\n### 1. Organização do Estado\n- Federação: União, Estados, DF e Municípios (art. 18)\n- Intervenção federal (art. 34) e estadual (art. 35)\n- Vedações constitucionais (art. 19)\n\n### 2. Repartição de Competências\n- Privativas da União (art. 22): Direito Civil, Penal, Trabalhista...\n- Comuns (art. 23): todos os entes\n- Concorrentes (art. 24): União + Estados + DF\n- Municipais (art. 30): interesse local\n\n### 3. Processo Legislativo (arts. 59-69)\n- Espécies: EC, LC, LO, lei delegada, MP, decreto legislativo, resolução\n- MP: relevância + urgência, 60+60 dias\n- LC: maioria absoluta; LO: maioria simples\n\n### 4. Poder Executivo\n- Presidente: mandato 4 anos, uma reeleição, 35 anos mínimo\n- Crime de responsabilidade: impeachment pelo Senado, 2/3\n- Medidas provisórias (art. 62)\n\n### 5. Poder Legislativo\n- Câmara: deputados, mandato 4 anos, proporcional\n- Senado: 81 senadores, 3 por Estado/DF, 8 anos\n- CPI: 1/3 dos membros, fato determinado, prazo certo`,
    summary: `## Resumo — Direito Constitucional II\n\n**Competência privativa da União (art. 22):** legislar sobre Direito civil, penal, processual, eleitoral, agrário, marítimo, aeronáutico, espacial, do trabalho. Estados podem legislar mediante lei complementar da União.\n\n**MP (art. 62):** relevância + urgência. 60 dias prorrogáveis por mais 60. Se não convertida: perde eficácia. Veda-se MP sobre: matéria penal, processual penal, lei orgânica do MP, organização do Judiciário...\n\n**LC × LO:**\n- LC: quórum de maioria absoluta + matéria reservada\n- LO: maioria simples\n- LC NÃO é hierarquicamente superior à LO\n\n**Senado:** 81 senadores (3/Estado). Mandato 8 anos. Renovação alternada: 1/3 e 2/3.\n\n**Impeachment:** câmara autoriza (2/3), senado julga (presidido pelo STF), condenação por 2/3 dos senadores.`,
    quiz: [
      { question: "Compete privativamente à União legislar sobre:", options: { A: "Proteção ao patrimônio histórico e paisagístico", B: "Direito civil, comercial, penal, processual, eleitoral e do trabalho", C: "Florestas, caça, pesca e fauna", D: "Previdência social" }, correct_answer: "B", explanation: "Art. 22, I CF: compete privativamente à União legislar sobre direito civil, comercial, penal, processual, eleitoral, agrário, marítimo, aeronáutico, espacial e do trabalho." },
      { question: "A Medida Provisória tem vigência inicial de:", options: { A: "30 dias, prorrogável por mais 30", B: "60 dias, prorrogável por mais 60", C: "90 dias improrrogáveis", D: "45 dias prorrogáveis" }, correct_answer: "B", explanation: "Art. 62, §3º CF: as MPs têm eficácia por 60 dias, prorrogável automaticamente por mais 60 dias." },
      { question: "O Senado Federal é composto por:", options: { A: "513 deputados eleitos proporcionalmente", B: "81 senadores, 3 por Estado e pelo DF", C: "54 senadores eleitos proporcionalmente", D: "27 senadores, um por Estado" }, correct_answer: "B", explanation: "Art. 46 CF: o Senado compõe-se de 3 representantes de cada Estado e do DF, totalizando 81 senadores." }
    ]
  },

  "Teoria Geral do Processo": {
    overview: `## Teoria Geral do Processo\n\nFundamentos do processo, jurisdição, ação e pressupostos processuais comuns a todo o Direito Processual.\n\n**Temas centrais:**\n- Jurisdição: conceito, características, princípios\n- Ação processual: teorias, condições, elementos\n- Processo: natureza jurídica e pressupostos\n- Princípios constitucionais do processo`,
    topics: `## Principais Tópicos\n\n### 1. Jurisdição\n- Poder-dever estatal de aplicar o Direito ao caso concreto\n- Princípios: investidura, aderência, indelegabilidade, inevitabilidade, inércia\n- Equivalentes: autotutela, autocomposição (mediação/conciliação), arbitragem\n\n### 2. Ação Processual\n- Teorias: imanentista, concreta, abstrata, eclética\n- Condições (CPC/2015): legitimidade + interesse processual\n- Elementos identificadores: partes + causa de pedir + pedido\n\n### 3. Processo\n- Relação jurídica triangular: juiz + autor + réu\n- Pressupostos de existência: jurisdição + demanda + partes\n- Pressupostos de validade: competência + capacidade + citação válida\n- Pressupostos negativos: litispendência + coisa julgada + perempção\n\n### 4. Princípios\n- Devido processo legal (art. 5º, LIV CF)\n- Contraditório e ampla defesa (LV)\n- Juiz natural, publicidade, duração razoável`,
    summary: `## Resumo — TGP\n\n**Jurisdição:** substitutividade (substitui vontade das partes) + definitividade (coisa julgada) + inércia (precisa ser provocada).\n\n**Condições da ação (CPC/2015):**\n1. Legitimidade das partes\n2. Interesse processual (necessidade + utilidade + adequação)\n*(possibilidade jurídica do pedido foi absorvida pelo mérito)*\n\n**Elementos da ação:** partes + causa de pedir (remota=fatos + próxima=fundamentos jurídicos) + pedido (imediato=providência + mediato=bem da vida).\n\n**Litispendência:** mesma ação proposta novamente (mesmas partes + causa de pedir + pedido) → extinção sem mérito.\n\n**Autocomposição:** as partes resolvem o litígio (transação, renúncia, reconhecimento do pedido, mediação, conciliação).`,
    quiz: [
      { question: "A inércia da jurisdição significa que:", options: { A: "O juiz não pode produzir provas de ofício", B: "O Poder Judiciário só atua quando devidamente provocado", C: "O processo não pode ser acelerado pelo juiz", D: "A jurisdição não pode ser delegada" }, correct_answer: "B", explanation: "A inércia da jurisdição (ne procedat judex ex officio) significa que o Estado-juiz só age quando provocado por uma demanda." },
      { question: "Os elementos identificadores da ação são:", options: { A: "Petição inicial, citação e sentença", B: "Partes, causa de pedir e pedido", C: "Jurisdição, competência e legitimidade", D: "Fatos, provas e decisão" }, correct_answer: "B", explanation: "Os elementos da ação são: partes (quem pede e contra quem), causa de pedir (fático + jurídico) e pedido (providência + bem da vida)." }
    ]
  },

  // ========== 4º PERÍODO ==========

  "Direitos Humanos": {
    overview: `## Direitos Humanos\n\nEstudo dos direitos inerentes à pessoa humana, reconhecidos no plano internacional e incorporados ao Direito interno.\n\n**Temas centrais:**\n- Fundamentos filosóficos dos Direitos Humanos\n- Dimensões/gerações dos direitos\n- Sistema Internacional (ONU) e Regional (OEA) de proteção\n- Direitos Humanos na CF/88\n- Responsabilidade internacional do Brasil`,
    topics: `## Principais Tópicos\n\n### 1. Fundamentos e Características\n- Universalidade: valem para todos\n- Indivisibilidade: não há hierarquia\n- Inalienabilidade, imprescritibilidade, irrenunciabilidade\n\n### 2. Dimensões\n- 1ª geração: direitos civis e políticos (liberdade)\n- 2ª geração: direitos econômicos, sociais e culturais (igualdade)\n- 3ª geração: direitos de solidariedade (fraternidade)\n- 4ª/5ª geração: direitos digitais, paz, democracia\n\n### 3. Sistema ONU\n- Carta da ONU (1945), DUDH (1948)\n- Pacto Internacional de Direitos Civis e Políticos (1966)\n- Pacto Internacional de Direitos Econômicos, Sociais e Culturais (1966)\n\n### 4. Sistema Interamericano (OEA)\n- Convenção Americana (Pacto de San José da Costa Rica, 1969)\n- Comissão e Corte Interamericana de Direitos Humanos\n- Caso Damião Ximenes Lopes × Brasil\n\n### 5. CF/88 e Tratados\n- Art. 5º, §2º: tratados de DH têm status de norma constitucional\n- Art. 5º, §3º (EC 45/2004): aprovados em 2 turnos com 3/5 → equivalem a EC`,
    summary: `## Resumo — Direitos Humanos\n\n**DUDH (1948):** declaração não vinculante, mas de enorme força moral. 30 artigos proclamando direitos universais.\n\n**Convenção Americana (1969):** tratado vinculante para os estados membros da OEA que a ratificaram. O Brasil ratificou em 1992.\n\n**Status dos tratados de DH no Brasil:**\n- Com votação do art. 5º, §3º (3/5, 2 turnos): equivalem a emenda constitucional\n- Sem esse rito: supralegal (acima das leis, abaixo da CF) — posição do STF\n\n**Corte Interamericana:** jurisdição contenciosa — condena o Brasil por violações. Ex: Caso Damião Ximenes Lopes (2006), primeiro caso contra o Brasil.\n\n**Controle de convencionalidade:** o Brasil deve aplicar a Convenção Americana, afastando lei interna incompatível.`,
    quiz: [
      { question: "Segundo o STF, os tratados de Direitos Humanos não aprovados com o rito do art. 5º, §3º CF têm status:", options: { A: "Constitucional", B: "Supralegal (acima das leis, abaixo da CF)", C: "Legal (equivalente às leis ordinárias)", D: "Infralegal" }, correct_answer: "B", explanation: "O STF fixou (RE 466.343) que os tratados de DH ratificados antes da EC 45/2004 têm status supralegal: acima das leis ordinárias, abaixo da Constituição." },
      { question: "A Convenção Americana de Direitos Humanos foi assinada em:", options: { A: "Paris, 1948", B: "Nova York, 1966", C: "San José da Costa Rica, 1969", D: "Viena, 1993" }, correct_answer: "C", explanation: "A Convenção Americana de Direitos Humanos, também chamada Pacto de San José da Costa Rica, foi assinada em 1969 na cidade de San José, Costa Rica." }
    ]
  },

  "Direito Processual Civil I": {
    overview: `## Direito Processual Civil I\n\n**Ementa:** Normas fundamentais do CPC/2015, jurisdição, ação, partes, litisconsórcio, intervenção de terceiros e competência.\n\n**Temas principais:**\n- Normas fundamentais (arts. 1º-12 CPC)\n- Teoria da Ação\n- Partes e capacidade processual\n- Litisconsórcio\n- Intervenção de terceiros\n- Competência`,
    topics: `## Principais Tópicos\n\n### 1. Normas Fundamentais (arts. 1º-12 CPC)\n- Boa-fé processual (art. 5º)\n- Cooperação (art. 6º)\n- Primazia do mérito (art. 4º)\n- Contraditório e duração razoável\n\n### 2. Condições da Ação\n- Legitimidade (ad causam): quem pode ser parte\n- Interesse processual: necessidade + adequação\n\n### 3. Litisconsórcio\n- Necessário × facultativo\n- Unitário × simples\n- Ativo, passivo, misto\n\n### 4. Intervenção de Terceiros\n- Assistência simples e litisconsorcial\n- Denunciação da lide\n- Chamamento ao processo\n- IDPJ (Incidente de Desconsideração da PJ)\n- Amicus curiae\n\n### 5. Competência\n- Absoluta (matéria, função, pessoa): improrrogável, arguível a qualquer tempo\n- Relativa (territorial, valor): prorrogável por não arguição tempestiva\n- Foro especial: imóveis (foro da situação), alimentos (domicílio do alimentando)`,
    summary: `## Resumo para Provas — DPC I\n\n**Normas fundamentais:** processo civil = justo + efetivo + tempestivo. Boa-fé é dever de todos (art. 5º).\n\n**Litisconsórcio necessário (art. 114):** obrigatório por lei ou pela natureza da relação. Sentença ineficaz se não todos forem citados.\n\n**Litisconsórcio unitário:** decisão deve ser uniforme para todos os litisconsortes.\n\n**Denunciação da lide (art. 125):** réu chama o terceiro com obrigação de regresso (ex: seguradora).\n\n**Competência absoluta × relativa:**\n- Absoluta: arguível a qualquer tempo, inclusive de ofício pelo juiz\n- Relativa: deve ser arguida na contestação; se não arguida, prorroga-se\n\n**Foro:** domicílio do réu (regra geral). Ações reais imobiliárias: foro da situação do imóvel (absoluta).`,
    quiz: [
      { question: "O litisconsórcio necessário caracteriza-se:", options: { A: "Pela faculdade das partes em formar o polo", B: "Por ser obrigatório por lei ou pela natureza da relação jurídica", C: "Pela necessidade de decisão uniforme", D: "Pela presença de mais de dois autores" }, correct_answer: "B", explanation: "Art. 114 CPC: o litisconsórcio é necessário quando por disposição de lei ou pela natureza da relação controvertida a eficácia da sentença depender da citação de todos." },
      { question: "As condições da ação no CPC/2015 são:", options: { A: "Legitimidade das partes e interesse processual", B: "Legitimidade, interesse e possibilidade jurídica do pedido", C: "Capacidade postulatória e legitimidade", D: "Interesse processual e representação regular" }, correct_answer: "A", explanation: "O CPC/2015 eliminou a possibilidade jurídica do pedido como condição autônoma, mantendo apenas legitimidade das partes + interesse processual (art. 17)." },
      { question: "Ações fundadas em direito real sobre imóveis devem ser ajuizadas:", options: { A: "No domicílio do réu", B: "No domicílio do autor", C: "No foro da situação do imóvel (competência absoluta)", D: "Na capital do Estado" }, correct_answer: "C", explanation: "Art. 47 CPC: para ações fundadas em direito real sobre imóvel é competente o foro da situação da coisa. Trata-se de competência absoluta." }
    ]
  },

  // ========== 5º PERÍODO ==========

  "Direito Administrativo I": {
    overview: `## Direito Administrativo I\n\n**Ementa:** Fontes, princípios, poderes e organização da Administração Pública, atos administrativos.\n\n**Temas principais:**\n- Regime jurídico-administrativo\n- Princípios expressos e implícitos (LIMPE)\n- Poderes administrativos\n- Organização: Adm. Direta e Indireta\n- Ato administrativo: elementos, atributos, extinção`,
    topics: `## Principais Tópicos\n\n### 1. Princípios (art. 37 CF) — LIMPE\n- Legalidade: só faz o que a lei permite\n- Impessoalidade: sem favorecimentos\n- Moralidade: ética e probidade\n- Publicidade: transparência\n- Eficiência (EC 19/98)\n\n### 2. Poderes Administrativos\n- Vinculado: sem margem de escolha\n- Discricionário: mérito (conveniência e oportunidade)\n- Hierárquico: relação de subordinação\n- Disciplinar: apurar e punir infrações\n- Regulamentar: decretos do Executivo\n- De polícia: limitar liberdades individuais em prol do interesse coletivo\n\n### 3. Organização Administrativa\n- Direta: União, Estados, DF, Municípios\n- Indireta: autarquias, fundações públicas, EPs, SEMs\n- Descentralização × desconcentração\n\n### 4. Ato Administrativo\n- Elementos (COFIM): Competência, Objeto, Forma, Motivo, Finalidade\n- Atributos: presunção de legitimidade, imperatividade, autoexecutoriedade, tipicidade\n- Revogação (mérito/ex nunc) × Anulação (ilegalidade/ex tunc)`,
    summary: `## Resumo — Direito Administrativo I\n\n**LIMPE (art. 37 CF):** Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência.\n\n**Legalidade administrativa:** diferente da legalidade privada. Adm. só pode fazer o que a lei AUTORIZA (não apenas o que a lei não proíbe).\n\n**Ato vinculado:** a lei não deixa margem (ex: aposentadoria compulsória).\n**Ato discricionário:** a lei confere margem de mérito (conveniência e oportunidade). Mérito não é controlável pelo Judiciário.\n\n**Revogação × Anulação:**\n| | Revogação | Anulação |\n|---|---|---|\n| Fundamento | Mérito (conveniência) | Ilegalidade |\n| Quem pode | Apenas a Adm. | Adm. e Judiciário |\n| Efeitos | Ex nunc (prospectivos) | Ex tunc (retroativos) |`,
    quiz: [
      { question: "O princípio da legalidade na Administração Pública significa:", options: { A: "O administrador pode fazer tudo que a lei não proíbe", B: "O administrador só pode agir quando e como a lei autoriza", C: "As leis se aplicam igualmente a particulares e ao Estado", D: "O Estado pode praticar atos sem autorização legal em casos de urgência" }, correct_answer: "B", explanation: "Na Adm. Pública, legalidade é mais estrita: o administrador SOMENTE pode agir com autorização legal prévia." },
      { question: "A anulação do ato administrativo ilegal produz efeitos:", options: { A: "Ex nunc (para o futuro)", B: "Ex tunc (retroativos, desde a origem)", C: "Apenas para terceiros de boa-fé", D: "A partir da publicação no DO" }, correct_answer: "B", explanation: "A anulação retira o ato viciado desde sua origem (efeitos ex tunc), pois ato ilegal nunca deveria ter produzido efeitos. Diferente da revogação (efeitos ex nunc)." },
      { question: "São atributos do ato administrativo:", options: { A: "Legalidade, moralidade e publicidade", B: "Presunção de legitimidade, imperatividade e autoexecutoriedade", C: "Competência, motivo e finalidade", D: "Vinculação, discricionariedade e tipicidade" }, correct_answer: "B", explanation: "Os atributos do ato administrativo são: presunção de legitimidade/veracidade, imperatividade (obriga terceiros), autoexecutoriedade e tipicidade." }
    ]
  },

  "Direito Empresarial I": {
    overview: `## Direito Empresarial I\n\n**Ementa:** Teoria da empresa, empresário, estabelecimento, sociedades e títulos de crédito.\n\n**Temas principais:**\n- Teoria da Empresa (CC/2002)\n- Empresário individual e sociedades\n- Estabelecimento empresarial\n- Tipos societários: LTDA e S/A\n- Títulos de crédito: cheque, NP, duplicata`,
    topics: `## Principais Tópicos\n\n### 1. Teoria da Empresa\n- Empresa: atividade econômica organizada\n- Empresário: quem exerce (art. 966 CC)\n- Não empresário: profissionais liberais (art. 966, §único)\n\n### 2. Sociedades\n- Simples × empresária\n- LTDA: responsabilidade limitada ao capital\n- S/A: aberta × fechada, ações, assembleias\n\n### 3. Títulos de Crédito\n- Princípios: cartularidade, literalidade, autonomia\n- Cheque: ordem de pagamento à vista, 6 meses para prescrição\n- Nota Promissória: promessa de pagamento\n- Duplicata: título causal (venda mercantil)\n\n### 4. Registro de Empresas\n- JUCEMG/Juntas Comerciais\n- Nome empresarial: firma × denominação\n- Livros empresariais obrigatórios`,
    summary: `## Resumo — Direito Empresarial I\n\n**Empresário (art. 966 CC):** exerce profissionalmente atividade econômica organizada para produção/circulação de bens/serviços.\n\n**Não é empresário:** profissional liberal (atividade intelectual), salvo se elemento de empresa.\n\n**Títulos de crédito — princípios:**\n- **Cartularidade:** direito incorporado ao documento (precisa do papel)\n- **Literalidade:** vale apenas o que está escrito no título\n- **Autonomia:** cada obrigação cambial é independente\n\n**Cheque:** ordem de pagamento à VISTA. Apresentação: 30 dias (mesma praça) / 60 dias (praça diferente). Prescrição: 6 meses do fim do prazo de apresentação.\n\n**Duplicata:** título causal. Só pode ser emitida na venda mercantil ou prestação de serviços. Aceite presumido se não houver recusa formal.`,
    quiz: [
      { question: "Segundo o art. 966 CC, considera-se empresário:", options: { A: "Qualquer pessoa que exerça atividade econômica", B: "Quem exerce profissionalmente atividade econômica organizada para produção ou circulação de bens/serviços", C: "Apenas pessoas jurídicas registradas na Junta Comercial", D: "Profissionais liberais que auferem renda" }, correct_answer: "B", explanation: "Art. 966 CC: empresário é quem exerce profissionalmente atividade econômica organizada. Profissionais liberais não são empresários (§único)." },
      { question: "O cheque é caracterizado como:", options: { A: "Promessa de pagamento a prazo", B: "Ordem de pagamento à vista, sacada contra o banco", C: "Título causal emitido em vendas mercantis", D: "Título que admite aceite bancário" }, correct_answer: "B", explanation: "O cheque é ordem de pagamento à VISTA, emitida pelo sacador ao banco (sacado). Não admite aceite." },
      { question: "O princípio da autonomia nos títulos de crédito significa:", options: { A: "O título circula independentemente de qualquer causa", B: "Cada obrigação cambial é independente das demais", C: "O título só vale se apresentado fisicamente", D: "O conteúdo é determinado pelo que está escrito" }, correct_answer: "B", explanation: "Autonomia: cada relação cambial é independente. O endossatário de boa-fé não sofre as exceções pessoais oponíveis aos portadores anteriores." }
    ]
  },

  "Direito do Trabalho I": {
    overview: `## Direito do Trabalho I\n\n**Ementa:** Princípios trabalhistas, contrato de trabalho, jornada, salário, férias e 13º.\n\n**Temas principais:**\n- Princípios do Direito do Trabalho\n- Relação de emprego × de trabalho\n- Contrato de trabalho: tipos e modalidades\n- Jornada e horas extras\n- Salário e remuneração\n- Férias e 13º salário`,
    topics: `## Principais Tópicos\n\n### 1. Princípios Trabalhistas\n- Proteção: in dubio pro operario, norma mais favorável, condição mais benéfica\n- Irrenunciabilidade/indisponibilidade\n- Continuidade da relação de emprego\n- Primazia da realidade\n- Inalterabilidade contratual lesiva\n\n### 2. Relação de Emprego (arts. 2º-3º CLT)\n- PONS: Pessoalidade, Onerosidade, Não eventualidade, Subordinação\n- Empregador: assume riscos econômicos\n- Empregado: presta serviço subordinado, não eventual, pessoal, oneroso\n\n### 3. Contrato de Trabalho\n- Prazo indeterminado (regra)\n- Prazo determinado: máx. 2 anos, prorrogável 1x\n- Experiência: máx. 90 dias (não é prazo determinado para efeito de 40% FGTS)\n- Teletrabalho (pós-Reforma 2017)\n\n### 4. Jornada\n- Art. 7º, XIII CF: 8h/dia e 44h/semana\n- Hora extra: adicional mínimo 50% (CF)\n- Máximo 2h extras/dia\n- Jornada 12x36: válida por ACT/CCT ou lei específica\n\n### 5. Remuneração\n- Salário: contraprestação básica\n- Remuneração: salário + gorjetas\n- Salário mínimo: nacional, irredutível\n- 13º: compulsório, pago em 2 parcelas`,
    summary: `## Resumo — Direito do Trabalho I\n\n**Requisitos da relação de emprego (PONS):**\nPessoalidade + Onerosidade + Não eventualidade (habitualidade) + Subordinação jurídica.\n\n**Primazia da realidade:** prevalece a realidade fática sobre o documento. Contrato verbal é válido na CLT.\n\n**Jornada:** 8h/dia, 44h/semana. Hora extra: mínimo 50% (pode ser maior por acordo). Compensação: banco de horas por acordo individual/coletivo.\n\n**Férias:** 30 dias (0-14 faltas) / 24 dias (15-23) / 18 dias (24-32) / 12 dias (33-32). Acréscimo constitucional de 1/3.\n\n**13º salário:** 1ª parcela entre fevereiro e novembro (ou nas férias, se solicitado). 2ª parcela até 20/12.\n\n**Reforma 2017 (Lei 13.467):** prevalência do negociado sobre o legislado para temas específicos. Teletrabalho regulamentado. Extinção das horas in itinere.`,
    quiz: [
      { question: "São requisitos da relação de emprego:", options: { A: "Autonomia, continuidade, risco e pessoalidade", B: "Pessoalidade, não eventualidade, subordinação e onerosidade", C: "Exclusividade, subordinação, onerosidade e habitualidade", D: "Subordinação, exclusividade, pessoalidade e continuidade" }, correct_answer: "B", explanation: "Os quatro elementos da relação de emprego (arts. 2º e 3º CLT): pessoalidade, não eventualidade (habitualidade), onerosidade e subordinação jurídica." },
      { question: "O adicional mínimo legal para horas extras é:", options: { A: "25%", B: "50%", C: "100%", D: "Depende do acordo coletivo" }, correct_answer: "B", explanation: "Art. 7º, XVI CF: adicional de, no mínimo, 50% sobre a hora normal. Acordos e convenções podem fixar percentuais maiores." },
      { question: "O princípio da primazia da realidade significa:", options: { A: "A CLT prevalece sobre a CF", B: "Os fatos reais prevalecem sobre a forma e documentos escritos", C: "O contrato escrito prevalece sobre a prática das partes", D: "O empregado deve provar todos os fatos alegados" }, correct_answer: "B", explanation: "Pelo princípio da primazia da realidade, o que importa é a realidade fática da relação de trabalho, independentemente do que esteja escrito." }
    ]
  },

  // ========== 6º PERÍODO ==========

  "Direito do Trabalho II": {
    overview: `## Direito do Trabalho II\n\n**Ementa:** Extinção do contrato de trabalho, FGTS, estabilidades, Direito Coletivo do Trabalho.\n\n**Temas principais:**\n- Rescisão contratual: modalidades e verbas\n- FGTS: depósitos, levantamento, multa rescisória\n- Estabilidades e garantias de emprego\n- Sindicatos, negociação coletiva\n- Greve`,
    topics: `## Principais Tópicos\n\n### 1. Extinção do Contrato\n- Dispensa sem justa causa: aviso prévio + FGTS + 40% multa\n- Dispensa com justa causa (art. 482 CLT): perde verbas rescisórias\n- Pedido de demissão: aviso prévio (pode ser dispensado pelo empregador)\n- Rescisão indireta (justa causa do empregador — art. 483 CLT)\n- Acordo entre partes (art. 484-A CLT, Reforma 2017)\n\n### 2. FGTS\n- Depósito: 8% da remuneração mensal\n- Multa rescisória: 40% (dispensa imotivada) ou 20% (acordo)\n- Levantamento: dispensa sem justa causa, aposentadoria, doença grave, etc.\n\n### 3. Estabilidades\n- Gestante: confirmação da gravidez até 5 meses após o parto\n- CIPA: representante dos empregados, 1 ano após mandato\n- Dirigente sindical: registro até 1 ano após mandato\n- Acidente de trabalho: 12 meses após a alta previdenciária\n\n### 4. Direito Coletivo\n- Sindicato: liberdade sindical, unicidade sindical\n- CCT (convenção coletiva) × ACT (acordo coletivo)\n- Dissídio coletivo: Tribunais do Trabalho`,
    summary: `## Resumo — Direito do Trabalho II\n\n**Dispensa sem justa causa:** aviso prévio proporcional (30 dias + 3 dias/ano, máx. 90 dias) + saldo salário + 13º proporcional + férias + 1/3 + FGTS + multa 40%.\n\n**Justa causa (art. 482 CLT):** improbidade, incontinência, negociação habitual, condenação criminal, desídia, embriaguez, violação de segredo, indisciplina, abandono de emprego, ato lesivo à honra, jogos proibidos, perda de habilitação.\n\n**Estabilidade da gestante:** mesmo que desconhecida a gravidez no momento da dispensa → nulidade da dispensa. Basta a comprovação posterior.\n\n**Negociado × legislado (Reforma 2017):** em determinadas matérias, o negociado coletivamente pode prevalecer sobre a lei (ex: banco de horas, jornada 12x36, PLR). Mas não pode reduzir direitos constitucionais.`,
    quiz: [
      { question: "Na dispensa sem justa causa, a multa do FGTS é de:", options: { A: "20% dos depósitos", B: "40% dos depósitos do período", C: "100% do último salário", D: "50% do FGTS acumulado" }, correct_answer: "B", explanation: "Art. 18 da Lei 8.036/90: na dispensa sem justa causa, o empregador deposita, a título de multa, 40% de todos os depósitos do FGTS do período." },
      { question: "A estabilidade da gestante:", options: { A: "Depende de comunicação prévia ao empregador", B: "Existe apenas durante a licença-maternidade", C: "Persiste mesmo se a gravidez era desconhecida no momento da dispensa", D: "Aplica-se apenas em contratos por prazo indeterminado" }, correct_answer: "C", explanation: "Súmula 244 TST: a garantia de emprego da gestante (art. 10, II, 'b' ADCT) independe do conhecimento do estado gravídico pela empregadora." }
    ]
  },

  "Direito Tributário I": {
    overview: `## Direito Tributário I\n\n**Ementa:** Sistema Tributário Nacional, tributos, competência tributária, princípios e imunidades.\n\n**Temas principais:**\n- Conceito e espécies de tributos\n- Competência tributária\n- Princípios constitucionais tributários\n- Imunidades tributárias\n- Obrigação tributária: fato gerador, sujeitos`,
    topics: `## Principais Tópicos\n\n### 1. Tributos (art. 3º CTN)\n- Conceito: prestação pecuniária compulsória, não constituinte de sanção\n- Espécies: impostos, taxas, contribuições de melhoria, contribuições especiais, empréstimos compulsórios\n\n### 2. Princípios Tributários\n- Legalidade (art. 150, I CF): criar/aumentar tributo por lei\n- Anterioridade (art. 150, III, 'b'): não cobrar no mesmo exercício\n- Anterioridade nonagesimal (art. 150, III, 'c'): mínimo 90 dias\n- Irretroatividade (art. 150, III, 'a')\n- Isonomia, vedação de confisco, liberdade de tráfego\n\n### 3. Imunidades (art. 150, VI CF)\n- Recíproca: entes federativos não tributam uns aos outros\n- Templos de qualquer culto\n- Partidos políticos, sindicatos, instituições educacionais/assistenciais s/ fins lucrativos\n- Livros, jornais, periódicos e o papel destinado à impressão\n\n### 4. Obrigação Tributária\n- Principal: pagar o tributo ou penalidade\n- Acessória: deveres formais (declarar, emitir nota)\n- Fato gerador: situação prevista em lei que faz nascer a obrigação`,
    summary: `## Resumo — Direito Tributário I\n\n**Tributo (art. 3º CTN):** prestação pecuniária compulsória, em moeda, que não constitua sanção por ato ilícito, instituída em lei, cobrada mediante atividade administrativa plenamente vinculada.\n\n**Espécies tributárias (pentapartição):**\n1. Impostos (fato gerador não vinculado)\n2. Taxas (poder de polícia ou serviço público divisível)\n3. Contribuições de melhoria (obra pública + valorização imobiliária)\n4. Contribuições especiais (sociais, interventivas, corporativas)\n5. Empréstimos compulsórios (guerra, calamidade, investimento urgente)\n\n**Princípio da anterioridade:** não pode cobrar tributo no mesmo exercício financeiro em que foi publicada a lei que o instituiu OU aumentou.\n\n**Exceções à anterioridade:** II, IE, IPI, IOF, IEG, empréstimos compulsórios de guerra.`,
    quiz: [
      { question: "Tributo, segundo o art. 3º do CTN, é:", options: { A: "Sanção por ato ilícito cobrada pelo Estado", B: "Prestação pecuniária compulsória, em moeda, não sanção por ato ilícito, instituída em lei", C: "Qualquer pagamento obrigatório ao Estado", D: "Contribuição voluntária para serviços públicos" }, correct_answer: "B", explanation: "Art. 3º CTN: tributo é toda prestação pecuniária compulsória, em moeda ou cujo valor nela se possa exprimir, que não constitua sanção de ato ilícito, instituída em lei e cobrada mediante atividade administrativa vinculada." },
      { question: "A imunidade recíproca prevista no art. 150, VI, 'a' CF:", options: { A: "Proíbe cobrar impostos de livros e jornais", B: "Veda aos entes federativos instituir impostos sobre patrimônio, renda ou serviços uns dos outros", C: "Impede a tributação de templos religiosos", D: "Isenta partidos políticos de qualquer tributo" }, correct_answer: "B", explanation: "Imunidade recíproca: é vedado à União, Estados, DF e Municípios instituir impostos sobre patrimônio, renda ou serviços, uns dos outros." }
    ]
  },

  // ========== 7º PERÍODO ==========

  "Direito Civil VI (Família)": {
    overview: `## Direito Civil VI — Família\n\n**Ementa:** Direito de família: casamento, união estável, filiação, alimentos e poder familiar.\n\n**Temas principais:**\n- Casamento: requisitos, impedimentos, efeitos\n- União estável\n- Regimes de bens\n- Filiação e reconhecimento\n- Poder familiar\n- Alimentos`,
    topics: `## Principais Tópicos\n\n### 1. Casamento\n- Requisitos: capacidade (16 anos + autorização), inexistência de impedimentos\n- Impedimentos absolutos (art. 1521 CC): proíbem casamento\n- Causas suspensivas (art. 1523 CC): apenas recomendam não casar\n- Nulidade × anulabilidade do casamento\n\n### 2. União Estável (art. 1723 CC)\n- Convivência pública, contínua e duradoura, com objetivo de constituir família\n- Impedimentos: mesmos do casamento (exceto separação de fato)\n- Conversão em casamento possível\n\n### 3. Regimes de Bens\n- Comunhão parcial de bens (regime legal): bens adquiridos na vigência\n- Comunhão universal: todos os bens (pré e pós)\n- Separação obrigatória: maiores de 70 anos, casamento com violação de impedimento\n- Participação final nos aquestos\n\n### 4. Filiação\n- Presunção de paternidade (art. 1597 CC)\n- Reconhecimento voluntário ou judicial\n- Igualdade entre filhos (art. 227, §6º CF)\n\n### 5. Alimentos\n- Binômio: necessidade × possibilidade\n- Alimentos provisionais, definitivos, gravídicos\n- Prisão civil do devedor (art. 5º, LXVII CF)`,
    summary: `## Resumo — Direito de Família\n\n**Regime legal (supletivo):** comunhão parcial de bens. Se os noivos não escolherem, este é o regime.\n\n**Separação obrigatória (art. 1641 CC):** maiores de 70 anos, quem casar com violação de impedimento ou falta de autorização.\n\n**Súmula 377 STF:** no regime de separação obrigatória comunicam-se os bens adquiridos onerosamente na constância do casamento (aquestos) — posição controvertida.\n\n**Guarda:** compartilhada é a regra (Lei 13.058/2014). Guarda unilateral: exceção.\n\n**Alimentos:** o alimentante paga conforme suas possibilidades; o alimentado recebe conforme sua necessidade (binômio). Presos civil por dívida alimentar: até 3 meses (regime fechado) ou 1-3 meses (regime domiciliar).`,
    quiz: [
      { question: "O regime de bens supletivo (quando os cônjuges não escolhem) é:", options: { A: "Comunhão universal de bens", B: "Comunhão parcial de bens", C: "Separação total de bens", D: "Participação final nos aquestos" }, correct_answer: "B", explanation: "Art. 1640 CC: não havendo convenção, ou sendo ela nula ou ineficaz, vigorará quanto aos bens entre os cônjuges o regime da comunhão parcial." },
      { question: "A prisão civil por dívida de alimentos:", options: { A: "É inconstitucional no Brasil", B: "É permitida pela CF/88 (art. 5º, LXVII)", C: "Só se aplica a alimentos definitivos", D: "Tem prazo máximo de 1 ano" }, correct_answer: "B", explanation: "Art. 5º, LXVII CF: não haverá prisão civil por dívida, SALVO a do responsável pelo inadimplemento voluntário e inescusável de obrigação alimentícia." }
    ]
  },

  // ========== 8º PERÍODO ==========

  "Ética Profissional": {
    overview: `## Ética Profissional — OAB\n\n**Ementa:** Estatuto da OAB, Código de Ética e Disciplina, prerrogativas e deveres do advogado.\n\n**Temas principais:**\n- Estatuto da Advocacia (Lei 8.906/94)\n- Código de Ética e Disciplina da OAB\n- Prerrogativas do advogado\n- Sigilo profissional\n- Incompatibilidades e impedimentos\n- Infrações disciplinares e sanções`,
    topics: `## Principais Tópicos\n\n### 1. Estatuto da OAB (Lei 8.906/94)\n- Requisitos para inscrição: bacharel em Direito + aprovação no Exame de Ordem\n- Capacidade postulatória privativa\n- Honorários: contratuais, sucumbenciais, arbitrados\n\n### 2. Prerrogativas (art. 7º)\n- Inviolabilidade do escritório e comunicações\n- Uso de cela especial\n- Receber intimações pessoalmente\n- Retirar autos de cartório por 5 dias (prazo exíguo: 1 hora)\n\n### 3. Deveres e Sigilo\n- Sigilo profissional: dever absoluto, perpetuidade\n- Lealdade, urbanidade, boa-fé\n- Proibição de captação de clientela (mercantilização)\n\n### 4. Incompatibilidades e Impedimentos\n- Incompatibilidade absoluta: magistrado, membro do MP, delegado, militar ativo\n- Incompatibilidade relativa: servidores da administração pública\n\n### 5. Infrações e Sanções (art. 34)\n- Censura (pena mais leve)\n- Suspensão\n- Exclusão (cancelamento da inscrição)\n- Multa`,
    summary: `## Resumo — Ética Profissional\n\n**Exame de Ordem:** obrigatório para exercício da advocacia. Bacharel sem aprovação não pode advogar (salvo estagiário regularmente inscrito).\n\n**Sigilo profissional:** dever absoluto. O advogado não pode revelar informações sigilosas mesmo após o fim do mandato. Não pode ser compelido a depor sobre elas.\n\n**Honorários sucumbenciais:** pertencem ao advogado (não ao cliente), salvo estipulação em contrário. São direito autônomo.\n\n**Incompatibilidade absoluta:** juízes, membros do MP, delegados de polícia, militares em atividade — não podem exercer a advocacia.\n\n**Sanções disciplinares (ordem crescente):** censura → suspensão → exclusão + multa (pode ser cumulada).`,
    quiz: [
      { question: "O sigilo profissional do advogado:", options: { A: "Cessa com o fim do mandato", B: "É relativo e pode ser afastado por ordem judicial", C: "É dever absoluto, de caráter perpétuo", D: "Não se aplica em processos criminais" }, correct_answer: "C", explanation: "O sigilo profissional é dever absoluto do advogado (art. 25 CED), de caráter perpétuo, mesmo após o término do mandato." },
      { question: "Os honorários sucumbenciais pertencem:", options: { A: "Ao cliente, que pode dispensá-los", B: "Ao advogado, sendo direito autônomo", C: "Ao Estado, revertendo ao Fundo de Aparelhamento", D: "À OAB, para custeio das atividades" }, correct_answer: "B", explanation: "Art. 85, §14 CPC e art. 23 EOAB: os honorários sucumbenciais são devidos ao advogado e pertencem a ele, constituindo direito autônomo, irrenunciável pelo cliente." }
    ]
  },

  // ========== 9º PERÍODO ==========

  "Direito do Consumidor": {
    overview: `## Direito do Consumidor\n\n**Ementa:** Código de Defesa do Consumidor, relação de consumo, responsabilidade, práticas comerciais e contratos.\n\n**Temas principais:**\n- Conceito de consumidor e fornecedor\n- Direitos básicos do consumidor (art. 6º CDC)\n- Responsabilidade pelo fato e pelo vício\n- Práticas abusivas\n- Contratos de consumo: cláusulas abusivas\n- Defesa do consumidor em juízo`,
    topics: `## Principais Tópicos\n\n### 1. Sujeitos da Relação de Consumo\n- Consumidor (art. 2º CDC): destinatário final\n- Fornecedor (art. 3º): desenvolve atividade de modo profissional/habitual\n- Consumidor equiparado (bystander, coletividade exposta, vítima de acidente)\n\n### 2. Direitos Básicos (art. 6º CDC)\n- Proteção à vida, saúde e segurança\n- Informação adequada e clara\n- Inversão do ônus da prova (art. 6º, VIII)\n- Acesso à justiça e efetiva reparação\n\n### 3. Responsabilidade\n- Pelo fato (art. 12-14): fato do produto/serviço → vício de segurança → dano → responsabilidade OBJETIVA\n- Pelo vício (art. 18-20): vício de qualidade/quantidade → sem dano além do produto\n- Responsabilidade solidária (cadeia de fornecimento)\n\n### 4. Práticas Abusivas (art. 39 CDC)\n- Venda casada\n- Recusa injustificada de atendimento\n- Publicidade enganosa e abusiva\n\n### 5. Cláusulas Abusivas (art. 51 CDC)\n- Nulas de pleno direito\n- Renúncia a indenização, transferência de responsabilidade, inversão do ônus unilateral`,
    summary: `## Resumo — Direito do Consumidor\n\n**Consumidor:** destinatário final fático e econômico do produto/serviço. Teoria finalista (STJ).\n\n**Responsabilidade pelo fato do produto (art. 12):** objetiva, independe de culpa. O fabricante, produtor, construtor e importador respondem. O comerciante: subsidiariamente (art. 13).\n\n**Inversão do ônus da prova (art. 6º, VIII):** quando for verossímil a alegação OU o consumidor for hipossuficiente. É ope judicis (por decisão do juiz).\n\n**Prazo para reclamação (art. 26):**\n- Vícios aparentes: 30 dias (não durável) / 90 dias (durável)\n- Vícios ocultos: contam do momento em que ficarem evidentes\n\n**Prazo prescricional (art. 27):** 5 anos para ação de reparação pelo fato do produto/serviço, contados do conhecimento do dano e da autoria.`,
    quiz: [
      { question: "A responsabilidade do fabricante por fato do produto no CDC é:", options: { A: "Subjetiva, dependendo da prova de culpa", B: "Objetiva, independente de culpa", C: "Solidária com o comerciante em todos os casos", D: "Limitada ao valor do produto" }, correct_answer: "B", explanation: "Art. 12 CDC: o fabricante, produtor, construtor e importador respondem independentemente da existência de culpa (responsabilidade objetiva) pela reparação dos danos causados pelo fato do produto." },
      { question: "O prazo para reclamar vícios aparentes em produtos duráveis é:", options: { A: "30 dias", B: "60 dias", C: "90 dias", D: "6 meses" }, correct_answer: "C", explanation: "Art. 26 CDC: o direito de reclamar pelos vícios aparentes caduca em 30 dias para produtos/serviços não duráveis e em 90 dias para produtos/serviços duráveis." }
    ]
  },

  "Direito Ambiental I": {
    overview: `## Direito Ambiental I\n\n**Ementa:** Fundamentos constitucionais, princípios, política nacional do meio ambiente e responsabilidade ambiental.\n\n**Temas principais:**\n- Direito ao meio ambiente (art. 225 CF)\n- Princípios do Direito Ambiental\n- Política Nacional do Meio Ambiente (Lei 6.938/81)\n- Licenciamento ambiental\n- Responsabilidade ambiental: civil, administrativa e penal\n- Lei de Crimes Ambientais (Lei 9.605/98)`,
    topics: `## Principais Tópicos\n\n### 1. Fundamento Constitucional (art. 225 CF)\n- Direito ao meio ambiente ecologicamente equilibrado: bem de uso comum do povo\n- Dever do Estado e da coletividade de defender e preservar\n- Estudo de Impacto Ambiental (EIA/RIMA)\n- Responsabilidade por dano ambiental: obrigação de reparar e sanção penal/administrativa\n\n### 2. Princípios Ambientais\n- Precaução: incerteza científica → não fazer\n- Prevenção: risco conhecido → evitar\n- Poluidor-pagador: quem polui paga o custo ambiental\n- Usuário-pagador\n- Desenvolvimento sustentável\n- Ubiquidade: meio ambiente em tudo\n\n### 3. PNMA (Lei 6.938/81)\n- Política Nacional do Meio Ambiente\n- SISNAMA: sistema de órgãos ambientais\n- CONAMA: Conselho Nacional do Meio Ambiente\n- EIA obrigatório para atividades de significativo impacto\n\n### 4. Responsabilidade Ambiental\n- Civil: objetiva (art. 14, §1º PNMA e art. 225, §3º CF), solidária, imprescritível para danos ao meio ambiente\n- Administrativa: multa, embargo, suspensão\n- Penal: crimes ambientais (Lei 9.605/98) — PJ pode ser responsabilizada penalmente`,
    summary: `## Resumo — Direito Ambiental I\n\n**Art. 225 CF:** todos têm direito ao meio ambiente ecologicamente equilibrado. Obrigação de defesa e preservação para as presentes e futuras gerações.\n\n**Precaução × Prevenção:**\n- **Precaução:** não há certeza científica sobre o risco → não agir ou agir com máxima cautela\n- **Prevenção:** risco é conhecido e comprovado → tomar medidas para evitar dano\n\n**Responsabilidade civil ambiental:** OBJETIVA (art. 14, §1º PNMA). Teoria do risco integral: não admite excludentes (caso fortuito, força maior, fato de terceiro).\n\n**Pessoa jurídica e crime ambiental:** o STF (AP 628) confirmou que PJ pode ser responsabilizada penalmente por crimes ambientais, independentemente da responsabilização das pessoas físicas.\n\n**EIA:** exigido para atividades potencialmente causadoras de significativa degradação ambiental (art. 225, §1º, IV CF).`,
    quiz: [
      { question: "A responsabilidade civil por dano ambiental é:", options: { A: "Subjetiva — exige comprovação de culpa", B: "Objetiva — independe de culpa", C: "Objetiva apenas para pessoas jurídicas", D: "Solidária apenas entre co-autores diretos" }, correct_answer: "B", explanation: "Art. 14, §1º PNMA e art. 225, §3º CF: a responsabilidade civil por dano ambiental é OBJETIVA — prescinde de culpa. Aplica-se a teoria do risco integral (STJ)." },
      { question: "O princípio da precaução distingue-se da prevenção porque:", options: { A: "A precaução se aplica quando o risco é certo e comprovado", B: "A precaução se aplica diante de incerteza científica sobre o risco", C: "A prevenção é mais abrangente que a precaução", D: "São sinônimos no Direito Ambiental" }, correct_answer: "B", explanation: "Precaução: incerteza científica sobre o risco → agir com cautela máxima ou não agir. Prevenção: risco conhecido e comprovado → tomar medidas para evitar o dano." }
    ]
  },

  // ========== 10º PERÍODO ==========

  "Mediação, Conciliação e Arbitragem": {
    overview: `## Mediação, Conciliação e Arbitragem\n\n**Ementa:** Métodos alternativos de resolução de conflitos (MARCs), mediação, conciliação e arbitragem.\n\n**Temas principais:**\n- Autocomposição × heterocomposição\n- Mediação (Lei 13.140/2015)\n- Conciliação no CPC/2015\n- Arbitragem (Lei 9.307/96)\n- CEJUSC e centros de resolução de conflitos`,
    topics: `## Principais Tópicos\n\n### 1. Métodos de Resolução de Conflitos\n- Autotutela: proibida em regra (exceção: desforço imediato)\n- Autocomposição: as partes resolvem (transação, renúncia, reconhecimento)\n- Heterocomposição: terceiro decide (arbitragem, jurisdição estatal)\n\n### 2. Mediação (Lei 13.140/2015)\n- Mediador: facilita o diálogo, não propõe solução\n- Voluntária e confidencial\n- Aplicável a direitos disponíveis e alguns indisponíveis\n- Extrajudicial e judicial\n\n### 3. Conciliação\n- Conciliador: pode propor soluções\n- Indicada para relações sem vínculo anterior\n- CEJUSC: Centro Judiciário de Solução de Conflitos e Cidadania\n- Audiência de conciliação/mediação: obrigatória no CPC (art. 334)\n\n### 4. Arbitragem (Lei 9.307/96)\n- Árbitro: decide como juiz privado\n- Cláusula compromissória (prévia) × compromisso arbitral (posterior ao litígio)\n- Sentença arbitral: título executivo judicial, não sujeita a recurso\n- Limitação: apenas direitos patrimoniais disponíveis`,
    summary: `## Resumo — Mediação, Conciliação e Arbitragem\n\n**Diferença fundamental:**\n- **Mediação:** mediador facilita sem propor solução\n- **Conciliação:** conciliador pode propor acordo\n- **Arbitragem:** árbitro DECIDE (como juiz privado)\n\n**Arbitragem (Lei 9.307/96):**\n- Apenas direitos patrimoniais disponíveis\n- Sentença arbitral = título executivo judicial (não homologação pelo Judiciário)\n- Cláusula compromissória é vinculante (STF/STJ)\n\n**CPC/2015:** audiência de conciliação/mediação é obrigatória, salvo se ambas as partes manifestarem desinteresse ou se a natureza do litígio não comportar autocomposição (art. 334).\n\n**Confidencialidade na mediação:** salvo acordo das partes ou obrigação legal, o mediador não pode ser testemunha nem revelar informações do procedimento.`,
    quiz: [
      { question: "Na mediação, o papel do mediador é:", options: { A: "Decidir o conflito com força vinculante", B: "Propor soluções para as partes escolherem", C: "Facilitar o diálogo para que as partes encontrem a solução", D: "Homologar acordo já firmado pelas partes" }, correct_answer: "C", explanation: "O mediador facilita a comunicação entre as partes, sem poder decisório e sem propor soluções. É técnica de autocomposição: as próprias partes constroem o acordo." },
      { question: "A sentença arbitral:", options: { A: "Precisa ser homologada pelo Poder Judiciário para ter eficácia", B: "É título executivo judicial, dispensando homologação", C: "É título executivo extrajudicial", D: "Pode ser revista pelo STJ em recurso especial" }, correct_answer: "B", explanation: "Art. 31 Lei 9.307/96: a sentença arbitral produz entre as partes os mesmos efeitos da sentença proferida pelos órgãos judiciais — é título executivo judicial (art. 515, VII CPC), dispensando homologação." }
    ]
  }
};

export function getSubjectContent(subject, type) {
  return CONTENT_DB[subject]?.[type] || null;
}

export function getSubjectQuiz(subject) {
  return CONTENT_DB[subject]?.quiz || null;
}
