export const FALLBACK_OVERVIEWS = {
  'Direito Constitucional I': `## Direito Constitucional I\n\n**Ementa:** Teoria da Constituição, Poder Constituinte, princípios fundamentais da CF/88, direitos e garantias fundamentais.\n\n**Temas principais:**\n- Conceito e classificação das constituições\n- Poder Constituinte originário e derivado\n- Princípios fundamentais (art. 1º ao 4º CF)\n- Direitos individuais e coletivos (art. 5º CF)\n- Direitos sociais (art. 6º ao 11º CF)\n- Nacionalidade e direitos políticos\n\n**Importância:** Base de todo o ordenamento jurídico brasileiro. Essencial para OAB e concursos públicos.`,

  'Direito Civil I (Parte Geral)': `## Direito Civil I — Parte Geral\n\n**Ementa:** Pessoas naturais e jurídicas, bens, fatos e atos jurídicos, negócio jurídico, prescrição e decadência.\n\n**Temas principais:**\n- Personalidade jurídica e capacidade civil\n- Pessoas jurídicas de direito público e privado\n- Classificação dos bens (móveis, imóveis, fungíveis)\n- Negócio jurídico: elementos, vícios, invalidade\n- Prescrição × Decadência\n- Domicílio civil\n\n**Importância:** Fundamento de todo o Direito Privado. Muito cobrado na OAB 1ª fase.`,

  'Direito Penal I': `## Direito Penal I\n\n**Ementa:** Princípios do Direito Penal, lei penal, teoria do crime, tipicidade, ilicitude e culpabilidade.\n\n**Temas principais:**\n- Princípios: legalidade, anterioridade, irretroatividade\n- Aplicação da lei penal no tempo e espaço\n- Teoria do Crime: conceito analítico (fato típico, ilícito e culpável)\n- Tipicidade formal e material\n- Causas excludentes de ilicitude (art. 23 CP)\n- Culpabilidade: imputabilidade, potencial consciência da ilicitude\n\n**Importância:** Base para toda a área penal. Amplamente cobrado em OAB e concursos.`,

  'Direito Processual Civil I': `## Direito Processual Civil I\n\n**Ementa:** Jurisdição, ação, processo, procedimento, partes e procuradores, litisconsórcio, intervenção de terceiros.\n\n**Temas principais:**\n- Normas fundamentais do CPC (arts. 1º ao 12)\n- Jurisdição, competência e organização judiciária\n- Teoria da Ação: condições e elementos\n- Pressupostos processuais\n- Partes e capacidade processual\n- Litisconsórcio facultativo e necessário\n- Intervenção de terceiros: denunciação, chamamento, amicus curiae\n\n**Importância:** Essencial para a prática forense e segunda fase da OAB.`,

  'Teoria Geral do Direito': `## Teoria Geral do Direito\n\n**Ementa:** Fontes do direito, norma jurídica, ordenamento jurídico, interpretação e aplicação do direito.\n\n**Temas principais:**\n- Conceito e fundamentos do Direito\n- Fontes formais e materiais do Direito\n- Norma jurídica: estrutura e classificação\n- Ordenamento jurídico e hierarquia das normas\n- Hermenêutica e interpretação jurídica\n- Analogia, costumes e princípios gerais\n\n**Importância:** Fundamenta a compreensão de todas as demais disciplinas jurídicas.`,

  'Direito do Trabalho I': `## Direito do Trabalho I\n\n**Ementa:** Princípios trabalhistas, contrato de trabalho, CTPS, jornada, salário, férias e 13º salário.\n\n**Temas principais:**\n- Princípios do Direito do Trabalho (proteção, norma mais favorável)\n- Relação de emprego × relação de trabalho\n- Requisitos da relação empregatícia (arts. 2º e 3º CLT)\n- Contrato de trabalho: tipos e modalidades\n- Jornada de trabalho e horas extras\n- Salário: conceito, modalidades, irredutibilidade\n- Férias e 13º salário\n\n**Importância:** Muito cobrado na OAB e concursos do TRT.`,

  'Direito Administrativo I': `## Direito Administrativo I\n\n**Ementa:** Fontes, princípios, poderes e organização da Administração Pública, atos administrativos.\n\n**Temas principais:**\n- Princípios: LIMPE (legalidade, impessoalidade, moralidade, publicidade, eficiência)\n- Organização administrativa: centralização e descentralização\n- Entidades da Administração Indireta\n- Ato administrativo: conceito, elementos, atributos\n- Vinculação e discricionariedade\n- Extinção dos atos administrativos\n\n**Importância:** Base para concursos públicos e para a segunda fase da OAB (área pública).`,

  'Direito Empresarial I': `## Direito Empresarial I\n\n**Ementa:** Teoria da empresa, empresário, estabelecimento, nome empresarial, registro, sociedades.\n\n**Temas principais:**\n- Teoria da Empresa (Código Civil 2002)\n- Conceito de empresário e atividade empresarial\n- Estabelecimento empresarial\n- Registro de Empresas (JUCEMG)\n- Sociedades simples e empresárias\n- Sociedade Limitada e Anônima\n- Títulos de crédito: nota promissória, cheque, duplicata\n\n**Importância:** Fundamental para a OAB (área empresarial) e assessoria jurídica corporativa.`,
};

export const FALLBACK_TOPICS = {
  'Direito Constitucional I': `## Principais Tópicos\n\n### 1. Teoria da Constituição\n- Conceito de Constituição\n- Classificações: rígida/flexível, escrita/consuetudinária, formal/material\n- Supremacia constitucional\n\n### 2. Poder Constituinte\n- Originário: ilimitado, incondicionado\n- Derivado: reformador, decorrente, revisor\n- Emendas constitucionais (art. 60 CF)\n- Cláusulas pétreas\n\n### 3. Princípios Fundamentais (arts. 1º-4º)\n- Fundamentos da República (SONFUD)\n- Objetivos fundamentais\n- Princípios das relações internacionais\n\n### 4. Direitos e Garantias Fundamentais\n- Art. 5º: 78 incisos — decorar os principais\n- Habeas corpus, mandado de segurança, habeas data\n- Mandado de injunção, ação popular\n\n### 5. Direitos Sociais (arts. 6º-11)\n- Direito à saúde, educação, trabalho, moradia\n- Direitos dos trabalhadores`,

  'Direito Penal I': `## Principais Tópicos\n\n### 1. Princípios Penais\n- Legalidade (nullum crimen sine lege)\n- Anterioridade, irretroatividade\n- Lesividade, fragmentariedade, subsidiariedade\n- Individualização da pena\n\n### 2. Lei Penal no Tempo\n- Irretroatividade da lei mais gravosa\n- Retroatividade da lei mais benéfica\n- Extra-atividade penal\n- Lex mitior em execução penal\n\n### 3. Teoria do Crime\n- Conceito analítico: fato típico + ilicitude + culpabilidade\n- Conduta (ação/omissão), resultado, nexo causal, tipicidade\n- Dolo (direto e eventual) × Culpa (imprudência, negligência, imperícia)\n\n### 4. Excludentes de Ilicitude (art. 23 CP)\n- Estado de necessidade\n- Legítima defesa\n- Estrito cumprimento do dever legal\n- Exercício regular do direito\n\n### 5. Culpabilidade\n- Imputabilidade penal\n- Embriaguez e doença mental\n- Erro de proibição`,
};

export const FALLBACK_SUMMARIES = {
  'Direito Constitucional I': `## Resumo para Provas — Direito Constitucional I\n\n### Pontos que SEMPRE caem em provas:\n\n**Cláusulas pétreas (art. 60 §4º CF):** forma federativa, voto direto/secreto/universal/periódico, separação dos poderes, direitos e garantias individuais.\n\n**Art. 5º — Os mais cobrados:**\n- Inc. XXXV: inafastabilidade da jurisdição\n- Inc. LIV: devido processo legal\n- Inc. LV: contraditório e ampla defesa\n- Inc. LXVIII: habeas corpus\n- Inc. LXIX: mandado de segurança\n\n**Poder Constituinte:** Originário = ilimitado. Derivado = limitado pelas cláusulas pétreas.\n\n**Emenda Constitucional:** Proposta por 1/3 da Câmara ou Senado, Presidente da República, ou mais da metade das Assembleias Legislativas. Aprovada por 3/5 em dois turnos em cada Casa.\n\n**Lembre:** A CF/88 é rígida, escrita, dogmática, promulgada e analítica.`,

  'Direito Civil I (Parte Geral)': `## Resumo para Provas — Direito Civil I\n\n### Pontos mais cobrados:\n\n**Personalidade × Capacidade:**\n- Personalidade: aptidão genérica para ser titular de direitos (nasce com vida)\n- Capacidade de direito: toda pessoa tem\n- Capacidade de fato: aptidão para exercer por si\n\n**Incapacidade (pós-EPD):**\n- Absolutamente incapazes: apenas menores de 16 anos\n- Relativamente incapazes: 16-18, ébrios habituais, pródigos\n\n**Negócio Jurídico — Vícios:**\n- Erro, dolo, coação, estado de perigo, lesão, fraude contra credores\n- Simulação → nulidade absoluta\n\n**Prescrição × Decadência:**\n- Prescrição: extingue a pretensão. Pode ser interrompida e suspensa.\n- Decadência: extingue o direito. Em regra, não se interrompe nem suspende.\n\n**Prazos importantes:** Prescrição geral = 10 anos. Reparação civil = 3 anos.`,
};

export function getFallbackContent(subject, type) {
  const map = {
    overview: FALLBACK_OVERVIEWS,
    topics: FALLBACK_TOPICS,
    summary: FALLBACK_SUMMARIES,
  };
  return map[type]?.[subject] || null;
}
