const ARTICLES = [
  // ===== CONSTITUIÇÃO FEDERAL =====
  { id: 'cf-1', law: 'cf', art: 'Art. 1º', title: 'Fundamentos da República', text: 'A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos:\nI - a soberania;\nII - a cidadania;\nIII - a dignidade da pessoa humana;\nIV - os valores sociais do trabalho e da livre iniciativa;\nV - o pluralismo político.\nParágrafo único. Todo o poder emana do povo, que o exerce por meio de representantes eleitos ou diretamente, nos termos desta Constituição.', keywords: ['fundamentos', 'soberania', 'cidadania', 'dignidade', 'pluralismo', 'república', 'democrático', 'SCDVP'] },
  { id: 'cf-2', law: 'cf', art: 'Art. 3º', title: 'Objetivos da República', text: 'Constituem objetivos fundamentais da República Federativa do Brasil:\nI - construir uma sociedade livre, justa e solidária;\nII - garantir o desenvolvimento nacional;\nIII - erradicar a pobreza e a marginalização e reduzir as desigualdades sociais e regionais;\nIV - promover o bem de todos, sem preconceitos de origem, raça, sexo, cor, idade e quaisquer outras formas de discriminação.', keywords: ['objetivos', 'desenvolvimento', 'pobreza', 'desigualdade', 'discriminação', 'sociedade justa'] },
  { id: 'cf-3', law: 'cf', art: 'Art. 5º', title: 'Direitos e Garantias Fundamentais', text: 'Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.\n\nLXVII - não haverá prisão civil por dívida, salvo a do responsável pelo inadimplemento voluntário e inescusável de obrigação alimentícia e a do depositário infiel;\nLXVIII - conceder-se-á habeas corpus sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção, por ilegalidade ou abuso de poder;\nLXIX - conceder-se-á mandado de segurança para proteger direito líquido e certo, não amparado por habeas corpus ou habeas data;\nLXXI - conceder-se-á mandado de injunção sempre que a falta de norma regulamentadora torne inviável o exercício dos direitos e liberdades constitucionais;\nLXXII - conceder-se-á habeas data:\na) para assegurar o conhecimento de informações relativas à pessoa do impetrante, constantes de registros ou bancos de dados de entidades governamentais ou de caráter público;\nLXXIII - qualquer cidadão é parte legítima para propor ação popular que vise a anular ato lesivo ao patrimônio público ou de entidade de que o Estado participe.', keywords: ['habeas corpus', 'mandado de segurança', 'mandado de injunção', 'habeas data', 'ação popular', 'direitos fundamentais', 'igualdade', 'liberdade', 'art 5', 'prisão civil', 'remédios constitucionais'] },
  { id: 'cf-4', law: 'cf', art: 'Art. 37', title: 'Administração Pública — Princípios', text: 'A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.\n\n§ 1º A publicidade dos atos, programas, obras, serviços e campanhas dos órgãos públicos deverá ter caráter educativo, informativo ou de orientação social.\n§ 4º Os atos de improbidade administrativa importarão a suspensão dos direitos políticos, a perda da função pública, a indisponibilidade dos bens e o ressarcimento ao erário, na forma e gradação previstas em lei.\n§ 6º As pessoas jurídicas de direito público e as de direito privado prestadoras de serviços públicos responderão pelos danos que seus agentes, nessa qualidade, causarem a terceiros, assegurado o direito de regresso contra o responsável nos casos de dolo ou culpa.', keywords: ['LIMPE', 'legalidade', 'impessoalidade', 'moralidade', 'publicidade', 'eficiência', 'administração pública', 'improbidade', 'responsabilidade objetiva'] },
  { id: 'cf-5', law: 'cf', art: 'Art. 60', title: 'Emenda Constitucional', text: 'A Constituição poderá ser emendada mediante proposta:\nI - de um terço, no mínimo, dos membros da Câmara dos Deputados ou do Senado Federal;\nII - do Presidente da República;\nIII - de mais da metade das Assembleias Legislativas das unidades da Federação.\n§ 2º A proposta será discutida e votada em cada Casa do Congresso Nacional, em dois turnos, considerando-se aprovada se obtiver, em ambos, três quintos dos votos dos respectivos membros.\n§ 4º Não será objeto de deliberação a proposta de emenda tendente a abolir:\nI - a forma federativa de Estado;\nII - o voto direto, secreto, universal e periódico;\nIII - a separação dos Poderes;\nIV - os direitos e garantias individuais.', keywords: ['emenda constitucional', 'cláusula pétrea', 'poder constituinte', 'reforma', 'três quintos', 'dois turnos', 'federativa', 'voto direto'] },
  { id: 'cf-6', law: 'cf', art: 'Art. 225', title: 'Meio Ambiente', text: 'Todos têm direito ao meio ambiente ecologicamente equilibrado, bem de uso comum do povo e essencial à sadia qualidade de vida, impondo-se ao Poder Público e à coletividade o dever de defendê-lo e preservá-lo para as presentes e futuras gerações.\n§ 1º Para assegurar a efetividade desse direito, incumbe ao Poder Público:\nIV - exigir, na forma da lei, para instalação de obra ou atividade potencialmente causadora de significativa degradação do meio ambiente, estudo prévio de impacto ambiental (EIA);\n§ 3º As condutas e atividades consideradas lesivas ao meio ambiente sujeitarão os infratores, pessoas físicas ou jurídicas, a sanções penais e administrativas, independentemente da obrigação de reparar os danos causados.', keywords: ['meio ambiente', 'ambiental', 'EIA', 'ecologicamente equilibrado', 'impacto ambiental', 'degradação'] },
  { id: 'cf-7', law: 'cf', art: 'Art. 7º', title: 'Direitos dos Trabalhadores', text: 'São direitos dos trabalhadores urbanos e rurais, além de outros que visem à melhoria de sua condição social:\nI - relação de emprego protegida contra despedida arbitrária ou sem justa causa;\nIII - fundo de garantia do tempo de serviço (FGTS);\nV - piso salarial proporcional à extensão e à complexidade do trabalho;\nVI - irredutibilidade do salário;\nXIII - duração do trabalho normal não superior a oito horas diárias e quarenta e quatro semanais;\nXVI - remuneração do serviço extraordinário superior, no mínimo, em cinquenta por cento à do normal;\nXVII - gozo de férias anuais remuneradas com, pelo menos, um terço a mais do que o salário normal;\nXVIII - licença à gestante, sem prejuízo do emprego e do salário, com a duração de cento e vinte dias;\nXXX - proibição de diferença de salários, de exercício de funções e de critério de admissão por motivo de sexo, idade, cor ou estado civil.', keywords: ['trabalhadores', 'FGTS', 'jornada', 'hora extra', 'férias', 'licença maternidade', 'salário', 'direitos trabalhistas', 'art 7'] },
  { id: 'cf-8', law: 'cf', art: 'Art. 5º, XXXIX/XL', title: 'Princípio da Legalidade Penal', text: 'XXXIX - não há crime sem lei anterior que o defina, nem pena sem prévia cominação legal;\nXL - a lei penal não retroagirá, salvo para beneficiar o réu.', keywords: ['legalidade penal', 'nullum crimen', 'irretroatividade', 'lei penal', 'retroatividade', 'beneficiar réu'] },

  // ===== CÓDIGO CIVIL =====
  { id: 'cc-1', law: 'cc', art: 'Art. 2º', title: 'Personalidade Civil', text: 'A personalidade civil da pessoa começa do nascimento com vida; mas a lei põe a salvo, desde a concepção, os direitos do nascituro.', keywords: ['personalidade', 'nascimento', 'nascituro', 'concepção', 'pessoa natural'] },
  { id: 'cc-2', law: 'cc', art: 'Art. 3º e 4º', title: 'Incapacidade', text: 'Art. 3º São absolutamente incapazes de exercer pessoalmente os atos da vida civil os menores de 16 (dezesseis) anos.\nArt. 4º São incapazes, relativamente a certos atos ou à maneira de os exercer:\nI - os maiores de dezesseis e menores de dezoito anos;\nII - os ébrios habituais e os viciados em tóxico;\nIII - aqueles que, por causa transitória ou permanente, não puderem exprimir sua vontade;\nIV - os pródigos.', keywords: ['incapacidade', 'absolutamente incapaz', 'relativamente incapaz', 'menor', '16 anos', '18 anos', 'pródigo', 'ébrio'] },
  { id: 'cc-3', law: 'cc', art: 'Art. 50', title: 'Desconsideração da Personalidade Jurídica', text: 'Em caso de abuso da personalidade jurídica, caracterizado pelo desvio de finalidade ou pela confusão patrimonial, pode o juiz, a requerimento da parte, ou do Ministério Público quando lhe couber intervir no processo, desconsiderá-la para que os efeitos de certas e determinadas relações de obrigações sejam estendidos aos bens particulares de administradores ou de sócios da pessoa jurídica beneficiados direta ou indiretamente pelo abuso.', keywords: ['desconsideração', 'personalidade jurídica', 'desvio de finalidade', 'confusão patrimonial', 'sócio', 'abuso'] },
  { id: 'cc-4', law: 'cc', art: 'Art. 186', title: 'Ato Ilícito', text: 'Aquele que, por ação ou omissão voluntária, negligência ou imprudência, violar direito e causar dano a outrem, ainda que exclusivamente moral, comete ato ilícito.', keywords: ['ato ilícito', 'responsabilidade civil', 'dano', 'culpa', 'negligência', 'imprudência'] },
  { id: 'cc-5', law: 'cc', art: 'Art. 206', title: 'Prescrição — Prazos', text: 'Prescreve:\n§ 1º Em 1 (um) ano: a pretensão dos hospedeiros ou fornecedores de víveres destinados a consumo no próprio estabelecimento;\n§ 2º Em 2 (dois) anos, a pretensão para haver prestações alimentares;\n§ 3º Em 3 (três) anos: a pretensão relativa a aluguéis; a que visa a reparação civil;\n§ 5º Em 5 (cinco) anos: a pretensão de cobrança de dívidas líquidas constantes de instrumento público ou particular.', keywords: ['prescrição', 'prazo prescricional', '3 anos', 'reparação civil', 'alimentos', 'aluguéis'] },
  { id: 'cc-6', law: 'cc', art: 'Art. 927', title: 'Responsabilidade Civil', text: 'Aquele que, por ato ilícito (arts. 186 e 187), causar dano a outrem, fica obrigado a repará-lo.\nParágrafo único. Haverá obrigação de reparar o dano, independentemente de culpa, nos casos especificados em lei, ou quando a atividade normalmente desenvolvida pelo autor do dano implicar, por sua natureza, risco para os direitos de outrem.', keywords: ['responsabilidade civil', 'reparar dano', 'objetiva', 'subjetiva', 'risco', 'culpa'] },
  { id: 'cc-7', law: 'cc', art: 'Art. 1.228', title: 'Propriedade', text: 'O proprietário tem a faculdade de usar, gozar e dispor da coisa, e o direito de reavê-la do poder de quem quer que injustamente a possua ou detenha.\n§ 1º O direito de propriedade deve ser exercido em consonância com as suas finalidades econômicas e sociais e de modo que sejam preservados, de conformidade com o estabelecido em lei especial, a flora, a fauna, as belezas naturais, o equilíbrio ecológico e o patrimônio histórico e artístico, bem como evitada a poluição do ar e das águas.', keywords: ['propriedade', 'usar gozar dispor', 'função social', 'domínio', 'posse'] },
  { id: 'cc-8', law: 'cc', art: 'Art. 1.640', title: 'Regime de Bens — Comunhão Parcial', text: 'Não havendo convenção, ou sendo ela nula ou ineficaz, vigorará, quanto aos bens entre os cônjuges, o regime da comunhão parcial.\nParágrafo único. Poderão os nubentes, no processo de habilitação, optar por qualquer dos regimes que este código regula. Quanto à forma, reduzir-se-á a termo a opção pela comunhão parcial, fazendo-se o pacto antenupcial por escritura pública, nas demais escolhas.', keywords: ['regime de bens', 'comunhão parcial', 'casamento', 'cônjuge', 'pacto antenupcial'] },
  { id: 'cc-9', law: 'cc', art: 'Art. 1.723', title: 'União Estável', text: 'É reconhecida como entidade familiar a união estável entre o homem e a mulher, configurada na convivência pública, contínua e duradoura e estabelecida com o objetivo de constituição de família.\n§ 1º A união estável não se constituirá se ocorrerem os impedimentos do art. 1.521; não se aplicando a incidência do inciso VI no caso de a pessoa casada se achar separada de fato ou judicialmente.', keywords: ['união estável', 'convivência', 'família', 'impedimentos', 'separação de fato'] },

  // ===== CÓDIGO PENAL =====
  { id: 'cp-1', law: 'cp', art: 'Art. 1º', title: 'Princípio da Legalidade', text: 'Não há crime sem lei anterior que o defina. Não há pena sem prévia cominação legal.', keywords: ['legalidade', 'nullum crimen', 'lei anterior', 'pena', 'crime', 'legalidade penal'] },
  { id: 'cp-2', law: 'cp', art: 'Art. 23', title: 'Excludentes de Ilicitude', text: 'Não há crime quando o agente pratica o fato:\nI - em estado de necessidade;\nII - em legítima defesa;\nIII - em estrito cumprimento de dever legal ou no exercício regular de direito.\nExcesso punível: O agente, em qualquer das hipóteses deste artigo, responderá pelo excesso doloso ou culposo.', keywords: ['excludente', 'ilicitude', 'estado de necessidade', 'legítima defesa', 'dever legal', 'excesso'] },
  { id: 'cp-3', law: 'cp', art: 'Art. 25', title: 'Legítima Defesa', text: 'Entende-se em legítima defesa quem, usando moderadamente dos meios necessários, repele injusta agressão, atual ou iminente, a direito seu ou de outrem.\nParágrafo único. Observados os requisitos previstos no caput deste artigo, considera-se também em legítima defesa o agente de segurança pública que repele agressão ou risco de agressão a vítima mantida refém durante a prática de crimes.', keywords: ['legítima defesa', 'agressão injusta', 'meios necessários', 'atual', 'iminente', 'moderadamente'] },
  { id: 'cp-4', law: 'cp', art: 'Art. 121', title: 'Homicídio', text: 'Matar alguém:\nPena - reclusão, de seis a vinte anos.\n§ 1º Se o agente comete o crime impelido por motivo de relevante valor social ou moral, ou sob o domínio de violenta emoção, logo em seguida a injusta provocação da vítima, o juiz pode reduzir a pena de um sexto a um terço.\n§ 2° Se o homicídio é cometido: I - mediante paga ou promessa de recompensa, ou por outro motivo torpe; II - por motivo fútil; III - com emprego de veneno, fogo, explosivo, asfixia, tortura ou outro meio insidioso; IV - à traição, de emboscada, ou mediante dissimulação: Homicídio qualificado: Pena - reclusão, de doze a trinta anos.', keywords: ['homicídio', 'matar', 'qualificado', 'privilegiado', 'reclusão', 'pena', 'violenta emoção'] },
  { id: 'cp-5', law: 'cp', art: 'Art. 155', title: 'Furto', text: 'Subtrair, para si ou para outrem, coisa alheia móvel:\nPena - reclusão, de um a quatro anos, e multa.\n§ 1º - A pena aumenta-se de um terço, se o crime é praticado durante o repouso noturno.\n§ 4º - A pena é de reclusão de dois a oito anos, e multa, se o crime é cometido: I - com destruição ou rompimento de obstáculo à subtração da coisa; II - com abuso de confiança, ou mediante fraude, escalada ou destreza.', keywords: ['furto', 'subtração', 'coisa alheia', 'qualificado', 'noturno', 'escalada', 'fraude'] },
  { id: 'cp-6', law: 'cp', art: 'Art. 157', title: 'Roubo', text: 'Subtrair coisa móvel alheia, para si ou para outrem, mediante grave ameaça ou violência a pessoa, ou depois de havê-la, por qualquer meio, reduzido à impossibilidade de resistência:\nPena - reclusão, de quatro a dez anos, e multa.\n§ 2º A pena aumenta-se de um terço até metade: I - se a violência ou ameaça é exercida com emprego de arma; II - se há o concurso de duas ou mais pessoas;\n§ 3º Se da violência resulta lesão corporal grave, a pena é de reclusão, de sete a dezoito anos; se resulta morte (latrocínio), reclusão de vinte a trinta anos.', keywords: ['roubo', 'grave ameaça', 'violência', 'latrocínio', 'arma', 'resultado morte'] },
  { id: 'cp-7', law: 'cp', art: 'Art. 171', title: 'Estelionato', text: 'Obter, para si ou para outrem, vantagem ilícita, em prejuízo alheio, induzindo ou mantendo alguém em erro, mediante artifício, ardil, ou qualquer outro meio fraudulento:\nPena - reclusão, de um a cinco anos, e multa, de quinhentos mil réis a dez contos de réis.\n§ 3º A pena aumenta-se de um terço se o crime é cometido em detrimento de entidade de direito público ou de instituto de economia popular, assistência social ou beneficência.', keywords: ['estelionato', 'fraude', 'vantagem ilícita', 'erro', 'ardil', 'artifício'] },
  { id: 'cp-8', law: 'cp', art: 'Arts. 312-317', title: 'Crimes contra a Administração Pública', text: 'Peculato (art. 312): Apropriar-se o funcionário público de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo, ou desviá-lo, em proveito próprio ou alheio. Pena - reclusão, de dois a doze anos, e multa.\n\nCorrupção Passiva (art. 317): Solicitar ou receber, para si ou para outrem, direta ou indiretamente, ainda que fora da função ou antes de assumi-la, mas em razão dela, vantagem indevida, ou aceitar promessa de tal vantagem. Pena - reclusão, de 2 a 12 anos, e multa.\n\nCorrupção Ativa (art. 333): Oferecer ou prometer vantagem indevida a funcionário público, para determiná-lo a praticar, omitir ou retardar ato de ofício. Pena - reclusão, de 2 a 12 anos, e multa.', keywords: ['peculato', 'corrupção', 'funcionário público', 'administração pública', 'crime servidor', 'concussão'] },

  // ===== CÓDIGO DE PROCESSO CIVIL =====
  { id: 'cpc-1', law: 'cpc', art: 'Arts. 1º-12', title: 'Normas Fundamentais', text: 'Art. 1º O processo civil será ordenado, disciplinado e interpretado conforme os valores e as normas fundamentais estabelecidos na Constituição da República Federativa do Brasil.\nArt. 4º As partes têm o direito de obter em prazo razoável a solução integral do mérito, incluída a atividade satisfativa.\nArt. 5º Aquele que de qualquer forma participa do processo deve comportar-se de acordo com a boa-fé.\nArt. 6º Todos os sujeitos do processo devem cooperar entre si para que se obtenha, em tempo razoável, decisão de mérito justa e efetiva.', keywords: ['normas fundamentais', 'boa-fé processual', 'cooperação', 'razoável duração', 'processo civil', 'CPC 2015'] },
  { id: 'cpc-2', law: 'cpc', art: 'Art. 17', title: 'Condições da Ação', text: 'Para postular em juízo é necessário ter interesse e legitimidade.', keywords: ['condições da ação', 'legitimidade', 'interesse processual', 'legitimidade ad causam'] },
  { id: 'cpc-3', law: 'cpc', art: 'Art. 47', title: 'Competência — Ações Imobiliárias', text: 'Para as ações fundadas em direito real sobre imóveis é competente o foro de situação da coisa.\n§ 1º O autor pode optar pelo foro de domicílio do réu ou pelo foro de eleição se o litígio não recair sobre direito de propriedade, vizinhança, servidão, divisão e demarcação de terras e de nunciação de obra nova.\n§ 2º A ação possessória imobiliária será proposta no foro de situação da coisa, cujo juízo tem competência absoluta.', keywords: ['competência', 'imóvel', 'situação da coisa', 'ação real', 'possessória', 'absoluta'] },
  { id: 'cpc-4', law: 'cpc', art: 'Art. 319', title: 'Petição Inicial — Requisitos', text: 'A petição inicial indicará:\nI - o juízo a que é dirigida;\nII - os nomes, os prenomes, o estado civil, a existência de união estável, a profissão, o número de inscrição no Cadastro de Pessoas Físicas ou no Cadastro Nacional da Pessoa Jurídica, o endereço eletrônico, o domicílio e a residência do autor e do réu;\nIII - o fato e os fundamentos jurídicos do pedido;\nIV - o pedido com as suas especificações;\nV - o valor da causa;\nVI - as provas com que o autor pretende demonstrar a verdade dos fatos alegados;\nVII - a opção do autor pela realização ou não de audiência de conciliação ou de mediação.', keywords: ['petição inicial', 'requisitos', 'partes', 'pedido', 'fatos', 'fundamentos', 'valor da causa', 'art 319'] },
  { id: 'cpc-5', law: 'cpc', art: 'Art. 485/487', title: 'Sentença — Extinção', text: 'Art. 485. O juiz não resolverá o mérito quando:\nI - indeferir a petição inicial;\nII - o processo ficar parado durante mais de 1 (um) ano por negligência das partes;\nIII - por não promover os atos e as diligências que lhe incumbir, o autor abandonar a causa por mais de 30 (trinta) dias;\nV - reconhecer a existência de perempção, de litispendência ou de coisa julgada;\nVI - verificar ausência de legitimidade ou de interesse processual.\nArt. 487. Haverá resolução de mérito quando o juiz: I - acolher ou rejeitar o pedido formulado na ação ou na reconvenção; II - decidir, de ofício ou a requerimento, sobre a ocorrência de decadência ou prescrição.', keywords: ['sentença', 'extinção', 'mérito', 'sem mérito', 'litispendência', 'coisa julgada', 'perempção', 'prescrição', 'decadência'] },

  // ===== CLT =====
  { id: 'clt-1', law: 'clt', art: 'Arts. 2º-3º', title: 'Empregador e Empregado', text: 'Art. 2º Considera-se empregador a empresa, individual ou coletiva, que, assumindo os riscos da atividade econômica, admite, assalaria e dirige a prestação pessoal de serviço.\nArt. 3º Considera-se empregado toda pessoa física que prestar serviços de natureza não eventual a empregador, sob a dependência deste e mediante salário.\nParágrafo único - Não haverá distinções relativas à espécie de emprego e à condição de trabalhador, nem entre o trabalho intelectual, técnico e manual.', keywords: ['empregado', 'empregador', 'relação de emprego', 'subordinação', 'não eventual', 'pessoalidade', 'salário', 'PONS'] },
  { id: 'clt-2', law: 'clt', art: 'Art. 58', title: 'Jornada de Trabalho', text: 'A duração normal do trabalho, para os empregados em qualquer atividade privada, não excederá de 8 (oito) horas diárias, desde que não seja fixado expressamente outro limite.\n§ 1º Não serão descontadas nem computadas como jornada extraordinária as variações de horário no registro de ponto não excedentes de cinco minutos, observado o limite máximo de dez minutos diários.\n§ 2º O tempo despendido pelo empregado desde a sua residência até a efetiva ocupação do posto de trabalho e para o seu retorno, caminhando ou por qualquer meio de transporte, não será computado na jornada de trabalho, por não ser tempo à disposição do empregador.', keywords: ['jornada', '8 horas', 'horas in itinere', 'registro ponto', 'duração trabalho'] },
  { id: 'clt-3', law: 'clt', art: 'Art. 482', title: 'Justa Causa — Empregado', text: 'Constituem justa causa para rescisão do contrato de trabalho pelo empregador:\na) ato de improbidade;\nb) incontinência de conduta ou mau procedimento;\nc) negociação habitual por conta própria ou alheia sem permissão do empregador;\ne) desídia no desempenho das respectivas funções;\nf) embriaguez habitual ou em serviço;\ng) violação de segredo da empresa;\nh) ato de indisciplina ou de insubordinação;\ni) abandono de emprego;\nj) ato lesivo da honra ou da boa fama;\nm) constituir o empregado em mora no pagamento das prestações do mútuo para a aquisição de habitação.', keywords: ['justa causa', 'rescisão', 'improbidade', 'abandono de emprego', 'desídia', 'indisciplina', 'embriaguez'] },
  { id: 'clt-4', law: 'clt', art: 'Art. 129', title: 'Férias', text: 'Todo empregado terá direito anualmente ao gozo de um período de férias, sem prejuízo da remuneração.\nArt. 130. Após cada período de 12 (doze) meses de vigência do contrato de trabalho, o empregado terá direito a férias, na seguinte proporção:\nI - 30 (trinta) dias corridos, quando não houver faltado ao serviço mais de 5 (cinco) vezes;\nII - 24 (vinte e quatro) dias corridos, quando houver tido de 6 (seis) a 14 (quatorze) faltas;\nIII - 18 (dezoito) dias corridos, quando houver tido de 15 (quinze) a 23 (vinte e três) faltas;\nIV - 12 (doze) dias corridos, quando houver tido de 24 (vinte e quatro) a 32 (trinta e duas) faltas.', keywords: ['férias', 'férias proporcionais', 'faltas', '30 dias', 'remuneração', 'descanso anual'] },

  // ===== CDC =====
  { id: 'cdc-1', law: 'cdc', art: 'Arts. 2º-3º', title: 'Consumidor e Fornecedor', text: 'Art. 2° Consumidor é toda pessoa física ou jurídica que adquire ou utiliza produto ou serviço como destinatário final.\nParágrafo único. Equipara-se a consumidor a coletividade de pessoas, ainda que indetermináveis, que haja intervindo nas relações de consumo.\nArt. 3° Fornecedor é toda pessoa física ou jurídica, pública ou privada, nacional ou estrangeira, bem como os entes despersonalizados, que desenvolvem atividade de produção, montagem, criação, construção, transformação, importação, exportação, distribuição ou comercialização de produtos ou prestação de serviços.', keywords: ['consumidor', 'fornecedor', 'destinatário final', 'relação de consumo', 'CDC', 'código defesa consumidor'] },
  { id: 'cdc-2', law: 'cdc', art: 'Art. 6º', title: 'Direitos Básicos do Consumidor', text: 'São direitos básicos do consumidor:\nI - a proteção da vida, saúde e segurança contra os riscos provocados por práticas no fornecimento de produtos e serviços considerados perigosos ou nocivos;\nII - a educação e divulgação sobre o consumo adequado dos produtos e serviços;\nIII - a informação adequada e clara sobre os diferentes produtos e serviços;\nIV - a proteção contra a publicidade enganosa e abusiva;\nV - a modificação das cláusulas contratuais que estabeleçam prestações desproporcionais;\nVIII - a facilitação da defesa de seus direitos, inclusive com a inversão do ônus da prova, a seu favor, no processo civil, quando, a critério do juiz, for verossímil a alegação ou quando for ele hipossuficiente;\nX - a adequada e eficaz prestação dos serviços públicos em geral.', keywords: ['direitos básicos', 'consumidor', 'inversão ônus prova', 'informação', 'publicidade enganosa', 'hipossuficiente'] },
  { id: 'cdc-3', law: 'cdc', art: 'Arts. 12-14', title: 'Responsabilidade pelo Fato do Produto', text: 'Art. 12. O fabricante, o produtor, o construtor, nacional ou estrangeiro, e o importador respondem, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos decorrentes de projeto, fabricação, construção, montagem, fórmulas, manipulação, apresentação ou acondicionamento de seus produtos.\nArt. 13. O comerciante é igualmente responsável, nos termos do artigo anterior, quando:\nI - o fabricante, o construtor, o produtor ou o importador não puderem ser identificados;\nII - o produto for fornecido sem identificação clara do seu fabricante, produtor, construtor ou importador;\nIII - não conservar adequadamente os produtos perecíveis.', keywords: ['responsabilidade', 'fato do produto', 'objetiva', 'fabricante', 'defeito', 'comerciante', 'consumidor'] },
  { id: 'cdc-4', law: 'cdc', art: 'Art. 26', title: 'Prazos para Reclamar', text: 'O direito de reclamar pelos vícios aparentes ou de fácil constatação caduca em:\nI - trinta dias, tratando-se de fornecimento de serviço e de produtos não duráveis;\nII - noventa dias, tratando-se de fornecimento de serviço e de produtos duráveis.\n§ 1° Inicia-se a contagem do prazo decadencial a partir da entrega efetiva do produto ou do término da execução dos serviços.', keywords: ['prazo', 'vício', 'reclamar', '30 dias', '90 dias', 'decadência', 'produto durável', 'não durável'] },
  { id: 'cdc-5', law: 'cdc', art: 'Art. 39', title: 'Práticas Abusivas', text: 'É vedado ao fornecedor de produtos ou serviços, dentre outras práticas abusivas:\nI - condicionar o fornecimento de produto ou de serviço ao fornecimento de outro produto ou serviço, bem como, sem justa causa, a limites quantitativos (venda casada);\nII - recusar atendimento às demandas dos consumidores, na exata medida de suas disponibilidades de estoque;\nIII - enviar ou entregar ao consumidor, sem solicitação prévia, qualquer produto, ou fornecer qualquer serviço;\nIV - prevalecer-se da fraqueza ou ignorância do consumidor.', keywords: ['práticas abusivas', 'venda casada', 'recusa atendimento', 'fornecedor', 'proibido'] },

  // ===== LEI MARIA DA PENHA =====
  { id: 'lmp-1', law: 'lei_maria_penha', art: 'Arts. 5º-7º', title: 'Violência Doméstica', text: 'Art. 5º Para os efeitos desta Lei, configura violência doméstica e familiar contra a mulher qualquer ação ou omissão baseada no gênero que lhe cause morte, lesão, sofrimento físico, sexual ou psicológico e dano moral ou patrimonial.\nArt. 7º São formas de violência doméstica e familiar contra a mulher, entre outras:\nI - a violência física;\nII - a violência psicológica;\nIII - a violência sexual;\nIV - a violência patrimonial;\nV - a violência moral.', keywords: ['violência doméstica', 'Maria da Penha', 'mulher', 'violência física', 'psicológica', 'sexual', 'patrimonial', 'gênero'] },
  { id: 'lmp-2', law: 'lei_maria_penha', art: 'Art. 41', title: 'Inaplicabilidade da Lei 9.099', text: 'Aos crimes praticados com violência doméstica e familiar contra a mulher, independentemente da pena prevista, não se aplica a Lei n. 9.099, de 26 de setembro de 1995.', keywords: ['lei 9099', 'JECRIM', 'violência doméstica', 'Maria da Penha', 'inaplicabilidade', 'juizado especial'] },

  // ===== LGPD =====
  { id: 'lgpd-1', law: 'lgpd', art: 'Art. 1º e 5º', title: 'LGPD — Conceitos Fundamentais', text: 'Art. 1º Esta Lei dispõe sobre o tratamento de dados pessoais, inclusive nos meios digitais, por pessoa natural ou por pessoa jurídica de direito público ou privado, com o objetivo de proteger os direitos fundamentais de liberdade e de privacidade e o livre desenvolvimento da personalidade da pessoa natural.\nArt. 5° Para os fins desta Lei, considera-se:\nI - dado pessoal: informação relacionada a pessoa natural identificada ou identificável;\nII - dado pessoal sensível: dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico;\nIII - banco de dados: conjunto estruturado de dados pessoais;\nIV - titular: pessoa natural a quem se referem os dados pessoais;\nV - controlador: pessoa natural ou jurídica, de direito público ou privado, a quem competem as decisões referentes ao tratamento de dados pessoais;\nVI - operador: pessoa natural ou jurídica, de direito público ou privado, que realiza o tratamento de dados pessoais em nome do controlador.', keywords: ['LGPD', 'dados pessoais', 'privacidade', 'controlador', 'operador', 'titular', 'sensível', 'tratamento'] },

  // ===== ECA =====
  { id: 'eca-1', law: 'eca', art: 'Art. 1º e 2º', title: 'ECA — Proteção Integral', text: 'Art. 1º Esta Lei dispõe sobre a proteção integral à criança e ao adolescente.\nArt. 2º Considera-se criança, para os efeitos desta Lei, a pessoa até doze anos de idade incompletos, e adolescente aquela entre doze e dezoito anos de idade.\nParágrafo único. Nos casos expressos em lei, aplica-se excepcionalmente este Estatuto às pessoas entre dezoito e vinte e um anos de idade.', keywords: ['ECA', 'criança', 'adolescente', 'proteção integral', '12 anos', '18 anos', 'menor'] },
  { id: 'eca-2', law: 'eca', art: 'Art. 112', title: 'Medidas Socioeducativas', text: 'Verificada a prática de ato infracional, a autoridade competente poderá aplicar ao adolescente as seguintes medidas:\nI - advertência;\nII - obrigação de reparar o dano;\nIII - prestação de serviços à comunidade;\nIV - liberdade assistida;\nV - inserção em regime de semiliberdade;\nVI - internação em estabelecimento educacional;\nVII - qualquer uma das previstas no art. 101, I a VI.', keywords: ['medidas socioeducativas', 'ato infracional', 'adolescente', 'internação', 'liberdade assistida', 'semiliberdade'] },

  // ===== CTN =====
  { id: 'ctn-1', law: 'ctn', art: 'Art. 3º', title: 'Conceito de Tributo', text: 'Tributo é toda prestação pecuniária compulsória, em moeda ou cujo valor nela se possa exprimir, que não constitua sanção de ato ilícito, instituída em lei e cobrada mediante atividade administrativa plenamente vinculada.', keywords: ['tributo', 'conceito tributo', 'prestação', 'compulsória', 'sanção', 'lei', 'CTN'] },
  { id: 'ctn-2', law: 'ctn', art: 'Art. 97', title: 'Princípio da Legalidade Tributária', text: 'Somente a lei pode estabelecer:\nI - a instituição de tributos, ou a sua extinção;\nII - a majoração de tributos, ou sua redução;\nIII - a definição do fato gerador da obrigação tributária principal e do seu sujeito passivo;\nIV - a fixação de alíquota do tributo e da sua base de cálculo;\nV - a cominação de penalidades para as ações ou omissões contrárias a seus dispositivos, ou para outras infrações nelas definidas;\nVI - as hipóteses de exclusão, suspensão e extinção de créditos tributários, ou de dispensa ou redução de penalidades.', keywords: ['legalidade tributária', 'tributo por lei', 'alíquota', 'fato gerador', 'base de cálculo', 'CTN'] },
];

export function searchVadeMecum(query, lawId) {
  if (!query || query.trim().length < 2) return [];

  const q = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const words = q.split(/\s+/).filter(w => w.length >= 2);

  const candidates = lawId
    ? ARTICLES.filter(a => a.law === lawId)
    : ARTICLES;

  const scored = candidates.map(article => {
    const haystack = [
      article.art,
      article.title,
      article.text,
      ...article.keywords
    ].join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');

    let score = 0;
    for (const word of words) {
      if (haystack.includes(word)) score += 1;
      if (article.keywords.some(k => k.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').includes(word))) score += 2;
      if ((article.art + ' ' + article.title).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').includes(word)) score += 3;
    }
    return { article, score };
  });

  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 5)
    .map(s => s.article);
}

export function formatArticleResult(articles) {
  if (!articles.length) return null;
  return articles.map(a =>
    `## ${a.art} — ${a.title}\n\n${a.text}`
  ).join('\n\n---\n\n');
}
